### ISSUE TITLE
 Unit tests for sidecar

### ISSUE THREAD

**Issue by Robmat05** [testground/testground#1003]
Please see Epic description for details on specific test builds

**Comment by coryschwartz** [comment]
This is partially completed, will solicit for reviews. 

This service consumes the testground sync API and the APIs for docker and kubernetes networking. The portion I've written mocks the networking driver to make sure when plans request a network change it gets currently passed on, but doesn't test the networking system itself.

**Comment by coryschwartz** [comment]
I have good comments on https://github.com/testground/testground/pull/939 that I can address tomorrow.
