### ISSUE TITLE
 Unit tests for pkg/rpc package (chunker and teeing OutputWriter). 

### ISSUE THREAD

**Issue by Robmat05** [testground/testground#1004]
Please see Epic description for details on specific tests

**Comment by coryschwartz** [comment]
I have part of this done in https://github.com/testground/testground/pull/1009 because I wanted to add the RecordedOutputWriter. Since the docker tests in that PR are in question, maybe I'll break out that part of it to a separate PR and take this as well.

**Comment by coryschwartz** [comment]
The PR I just added has the rpctest broken out. See https://github.com/testground/testground/pull/1015  was originally written in https://github.com/testground/testground/pull/1009 but I stripped out the RPC component.
