### ISSUE TITLE
sidecar errors for a test run should be shown in test output

### ISSUE THREAD

**Issue by willscott** [testground/testground#1025]
#### Version information:
b1773a47ede14f027c74b253a1a01caec0a6256d
x86_64 / debian

#### Description:
when debugging / setting up a new test, a logic error meant multiple containers were requesting the same configured IP address from the sidecar. The sidecar in it's docker logs reports an error "address already in use" in failing to perform this action, but the observed behavior when running the test is that the context for the `configureNetwork` command times out, and no error is provided besides that the command failed.

It would be great for the underlying sidecar error to be exposed in the diagnostic errors for the test to help with investigation / debugging

**Comment by nonsense** [comment]
I've added a PR that addresses this for `local:docker` runner. We can't do the same for `cluster:k8s`, because it is not a good idea to tail logs from 100 of containers - we need proper log aggregation tooling across the whole stack for Kubernetes - ELK, or something like that.
