### ISSUE TITLE
Create Cluster in Testground for DRand team

### ISSUE THREAD

**Issue by Robmat05** [testground/testground#1038]
DRand is interested in having a cluster for regularly running our test plans to watch how some of our metrics track over time as the code base changes

Object and success criteria scope: 
We will create an 8 node cluster for their stated purpose of their setting a testplan running hourly against their master code base, and viewing some of the RecordPoint's charted on a dashboard via Influxdb and Grafana

TG team will set up cluster and script the periodic execution. Each iteration would increment the cluster resources, run the test plan, and scale down the cluster

**Comment by coryschwartz** [comment]
The cluster has been created in us-west-2

This is,  of course, a temporary solution until we get testground as-a-service up and running. I wrote this to automate running the plan on a simple timer.

https://github.com/coryschwartz/tgrunner

We can move this code to testground if we want to, but this is probably throw-away code once testground-as-a-service finally arrives.
