### ISSUE TITLE
docs site: missing information for test plan outputs

### ISSUE THREAD

**Issue by nholland94** [testground/testground#1040]
## Description

The following portion of documentation makes mention of a predefined JSON schema a test plan is intended to output. I have been unable to find this schema definition on the github repos related to testground. A JSON schema link would be great. Even better would be if the JSON schema for the test plan output was also well documented from the docs site so that it can be clear to those who are interested in using alternative languages for writing test plans.

https://docs.testground.ai/concepts-and-architecture/test-structure#the-test-plan-less-than-greater-than-testground-contract

## What defines this endeavour to be complete?

- [ ] Test plan output JSON schema exists and is linked to
- [ ] Optional: the test plan outputs are documented on the docs site (possibly in a section about implementing custom test plans)

**Comment by coryschwartz** [comment]
@nholland94 that is great feedback and I am glad you reached out!

We'll take this suggestion to better document the communication interface between testground and test plans. Providing a json schema link would be very useful for sure.

In the mean time until we get that done, I would say to have a look at how it's done in https://github.com/testground/sdk-go.  In particular, how the sdk  [emits events](https://github.com/testground/sdk-go/blob/master/runtime/runenv_events.go) These events get displayed to the user and saved in the output. Saved outputs, log files, binary assets, etc are captured by testground but their content is not necessarily structured.

We expect there to be other build languages and runtime soon, but we aren't all the way there yet.  You might have luck building with the `docker:generic` builder (you provide your own Dockerfile) or using the `hooks` feature recently added to the `docker:go` builder, with which you can include files of any kind, including code from other languages. There are currently no plan SDKs aside from the SDK for go.

Thank you for the contribution.

**Comment by nonsense** [comment]
Not sure why this is closed. I don't think we have fixed the documentation with respect to the JSON schema of the outputs as suggested in the issue.

**Comment by coryschwartz** [comment]
I added a section that includes some basic HTTP API information.

this is subject to change in the future (more will be added for TAAS). Maybe we should place this onto a schema directory somewhere or version as we make changes to the api. Nevertheless, here is a doc page with our currently-supported requests.

https://docs.testground.ai/concepts-and-architecture/client-server-communication
