### ISSUE TITLE
introduce concept of jobs to Testground

### ISSUE THREAD

**Issue by nonsense** [testground/testground#1043]
Testground should formally models the concept of “jobs”:
- Build and run are jobs.
- Not all jobs execute synchronously any longer.
- They are queued in the job scheduling queue (R03).

See R2 under https://docs.google.com/document/d/19dA5SsiVDt43rnaSiaxNtXYYBN_MVaikvi0JFvpYlos/edit?ts=5ecaad42#

**Comment by coryschwartz** [comment]
If we decide to go with https://github.com/testground/testground/pull/1051ffor R03  then then we probably need to save the multipart request from the client somewhere. EFS? In the database also? I'm not sure where we want to put that.

I included in the model for the task a "state" to communicate to the client where the job is in the process.
