### ISSUE TITLE
decide on public forum for Testground

### ISSUE THREAD

**Issue by nonsense** [testground/testground#1049]
We should have some kind of public forum or public chat for the community. Ideas so far include:
1. Section on discuss.ipfs.io
2. New discourse installation for Testground (discuss.testground.ai ?)
3. Chat - Maybe Discord?

@raulk @coryschwartz @Robmat05 let's think about this and briefly discuss on next team meeting.

**Comment by raulk** [comment]
I'll ping GitHub and ask if we can opt-in to the GitHub Discussions beta: https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions

**Comment by nonsense** [comment]
For now we use a sub forum at https://discuss.ipfs.io - https://discuss.ipfs.io/c/testground/27
