### ISSUE TITLE
testground collect creates zip file with wrong file extension

### ISSUE THREAD

**Issue by jfietz** [testground/testground#1065]
#### Version information:
commit 98963f4 (HEAD -> master, tag: v0.5.2, origin/master, origin/HEAD)

#### Description:
I was following the tutorial on how to create test plans. At some point, there is a reference to the command `testground collect`. 

Commands up to here:

    $ testground run single --plan=network --testcase=ping-pong --builder=exec:go --runner=local:exec --instances=2
    $ testground collect --runner local:exec c4d4c3d2-acb5-11ea-be15-5a2fe2aa3bb5

    Jun 12 14:23:44.486307  INFO    using home directory: [..]/testground
    Jun 12 14:23:44.486361  INFO    no .env.toml found at [..]/testground/.env.toml; running with defaults
    Jun 12 14:23:44.486372  INFO    testground client initialized   {"addr": "localhost:8042"}

    >>> Result:

    Jun 12 14:23:44.488425  INFO    created file: c4d4c3d2-acb5-11ea-be15-5a2fe2aa3bb5.tgz

However, unzipping with tar xzf fails. This is due to the file being a zip archive, not a gzip compressed tar.

    $ file c4d4c3d2-acb5-11ea-be15-5a2fe2aa3bb5.tgz
    c4d4c3d2-acb5-11ea-be15-5a2fe2aa3bb5.tgz: Zip archive data, at least v2.0 to extract`

Expected output: `c4d4c3d2-acb5-11ea-be15-5a2fe2aa3bb5.tar.gz: gzip compressed data, last modified: Fri Jun 12 14:25:51 2020, from Unix, original size modulo 2^32 10240`

Suggestion: Either rename the file to .zip instead of tgz, or package as a tar file.

**Comment by nonsense** [comment]
@jfietz thanks for filing. There is indeed an inconsistency between the (`local:exec` + `local:docker`) and the `cluster:k8s` runners. The `cluster:k8s` is returning a `gzip compressed data, max compression, from Unix`, whereas the other two are returning `Zip archive data`.

We will definitely address this in a future release.

**Comment by nonsense** [comment]
@jfietz slightly off-topic: I notice that you are trying to run `network/ping-pong` on `local:exec` - this won't do anything, because the `network/ping-pong` test plan needs the `sidecar` (for traffic shaping) and `local:exec` doesn't have those capabilities - we currently don't have traffic shaping on the `local:exec` runner.

You can try the `local:docker` runner if you want to run this test plan!

**Comment by jfietz** [comment]
@nonsense OT response: Thanks for pointing that out. Figured that out myself after diving into the code for it, but `local:docker` timed out on my first try (from what I can see, I probably haven't setup sidecar correctly yet).
