### ISSUE TITLE
Pods don't get scheduled on k8s if composition group name is too long

### ISSUE THREAD

**Issue by yusefnapora** [testground/testground#1068]
#### Version information:

running from master, shortly after v0.5.2 release:

commit 25a3d63acf604cf2de686fdda472c2a1a5482eb0

EC2 VM, intel x86, 64bit

#### Description:
This is an odd one.

I'm trying to run a composition with three groups: `bootstrappers`, `servers`, and `sybils`. Everything works as expected with the `local:docker` runner.

When I try to run with the `cluster:k8s` runner, the pods in the `bootstrappers` group never get scheduled. For example, in a composition with 60 nodes total, 20 of which are bootstrappers, only 40 nodes show in the "pending" state in the testground debug logs, and `kubectl get pods` doesn't show any tagged as bootstrappers.

What's odd is that it _does_ work if I rename the group to `boot` - with the shorter name the pods all get scheduled correctly. 

Adding to the strangeness, if I try to schedule 16 instances in a group named `bootstr` (or any other 7 character name, e.g. `abcdef`), it will only schedule 10 of them. If I drop down to six characters, they all get scheduled.

My guess is that this is related to run IDs now being represented as full UUIDs instead of shorter strings - I'm assuming we're hitting some odd length limit on container names now that the run id is taking up more space in the name.

**Comment by Robmat05** [comment]
work being performed in #1067
