### ISSUE TITLE
testground/sdk-go: runenv.StringParam() returns quoted string

### ISSUE THREAD

**Issue by jfietz** [testground/testground#1069]
#### Version information:
testground/sdk-go\@v0.2.2
#### Description:
My manifest defines testcases as:

```
  [[testcases]]
  name= "native"
  instances = { min = 2, max = 2, default = 2 }
     [testcases.params]
     msg_size = { type = "int", desc = "Message size per send operation", unit = "Bytes", default = 1000 }
     protocol = {type = "string", desc = "Protocol (tcp or udp)", default = "udp"}
```

When I read the protocol parameter in my testplan, it is parsed as `"udp"`, not as `udp`. 

Declaring the default without quotes results in an error as well: 
`failed to resolve test plan: failed to parse manifest file at ~/testground/plans/throughput/manifest.toml: Near line 31 (last key parsed 'testcases.params.protocol.default'): expected value but found "udp" instead`

Small side note: The documentation also says that if its unset, it will return an empty string, but it actually panics: https://github.com/testground/sdk-go/blob/f97396ea1821f4b45cb995a4319bd06fd04abfca/runtime/runparams.go#L143

**Comment by raulk** [comment]
This should be solved by https://github.com/testground/testground/pull/648, but we haven't had the bandwidth to write a unit test. Fancy helping out, @jfietz? 😇

**Comment by jfietz** [comment]
@raulk I'll look into it, absolutely

**Comment by raulk** [comment]
The fix for this was merged a few months ago in https://github.com/testground/testground/pull/1089. Thanks for the report!
