### ISSUE TITLE
Use random free ports instead of statically assigned ports

### ISSUE THREAD

**Issue by hacdias** [testground/testground#1114]
While reviewing #1108, @nonsense suggested to randomly let Docker assign ports to our services instead of using static ports. That would solve the collisions problems we face.

> This is just another example that supporting so many runners is somewhat difficult, considering that we want to replicate the experience and behaviour across runners (influx, grafana, jupyter, (previously there were some attempts to also include prometheus) and what-not), which is especially difficult when you have no isolation on the machine... at least with Docker we get that isolation.
> 
> We might be more successful if we just allow Docker to bind all auxiliary services to random ports, and not lock static ports - then I think Docker makes sure there are no collisions. We would just need to introduce code for service discovery though.

Usually randomly assigned ports are high and thus it's much more unlikely for someone to start some service on that port on purpose too.

**Comment by raulk** [comment]
The problem with doing this is that the `local:exec` runner will need to query the docker daemon to discover the effective random host port, so it can pass it to testground test instances via an env variable.

This would also complicate debugging and general usage:

* if you want to debug the sync service, first you have to figure out which port Redis is running on.
* if you want to view metrics, you have to figure out which port InfluxDB is running on.

In general, it makes things pretty unergonomic, as it requires introducing an extra step (finding out the port) for many human action.

I think the healthcheck is just fine.
