### ISSUE TITLE
Testground daemon address error

### ISSUE THREAD

**Issue by dgrisham** [testground/testground#1133]
#### Version information:

Running Arch Linux. Just updated to Go 15, but I ran this yesterday and am relatively certain I was on Go 14 then (with the same issue).

```
$ git log | head -n1      
commit 13c74dbb398b051eb50e52c73cd2e4d11c416b93

$ uname -a               
Linux baau 5.8.1-arch1-1 #1 SMP PREEMPT Wed, 12 Aug 2020 18:50:43 +0000 x86_64 GNU/Linux

$ go version
go version go1.15 linux/amd64
```

#### Description:

Hi! I'm trying to run testground tests, but something seems to have broken in a recent update (I had it working around 3-4 weeks ago). I've built testground from the most recent commit on `master`, and upon running a test I get an error around the testground daemon address:

```
$ testground run single --plan=network --testcase=ping-pong --builder=docker:go --runner=local:docker --instances=2
Aug 19 20:33:49.595669  INFO    created a synthetic composition file for this job; all instances will run under singleton group "single"
Aug 19 20:33:49.595700  INFO    using home directory: /home/grish/src/ipfs/testground/testground-tests
Aug 19 20:33:49.595720  INFO    no .env.toml found at /home/grish/src/ipfs/testground/testground-tests/.env.toml; running with defaults
Aug 19 20:33:49.595726  INFO    testground client initialized   {"addr": "localhost:8042"}
Aug 19 20:33:49.595976  INFO    using home directory: /home/grish/src/ipfs/testground/testground-tests
Aug 19 20:33:49.595997  INFO    no .env.toml found at /home/grish/src/ipfs/testground/testground-tests/.env.toml; running with defaults
Aug 19 20:33:49.596002  INFO    testground client initialized   {"addr": "localhost:8042"}
Aug 19 20:33:49.596146  INFO    test plan source at: /home/grish/src/ipfs/testground/testground-tests/plans/network
Post "localhost:8042/build": unsupported protocol scheme "localhost"
```

I saw a similar issue at https://github.com/testground/testground/issues/1123, but I wasn't quite sure what their solution was exactly. I tried updating [this address](https://github.com/testground/testground/blob/master/pkg/config/loader.go#L16) to `http://localhost:8042`, which I thought was their solution, but upon rebuilding and rerunning the testground daemon I get:

```
$ testground daemon

Aug 19 20:14:17.187933  INFO    using home directory: /home/grish/src/ipfs/testground/testground-tests
Aug 19 20:14:17.187980  INFO    no .env.toml found at /home/grish/src/ipfs/testground/testground-tests/.env.toml; running with defaults
listen tcp: address http://localhost:8042: too many colons in address
```

Any thoughts? Curious if it's just me. Thanks!

**Comment by raulk** [comment]
Thanks for reporting, and sorry for the trouble! This has been reported twice now (cc @dirkmc). It was likely a regression introduced by this PR: https://github.com/testground/testground/pull/1118

Gonna have a quick look now.
