### ISSUE TITLE
Error while doing libp2p ping test

### ISSUE THREAD

**Issue by sujith2s** [testground/testground#1169]
Hello,

Interested in the libp2p projects, so I was trying to setup the testground setup.
Tried of executing the ping test from the libp2p. 
I am getting error logs continuously, after the container creation and start.
using the latest code from testground master branch.

command used
-----------------
testground run single --plan libp2p/ping --testcase ping --builder docker:go --runner local:docker --run-cfg log_level=`true` --instances=4

Error log
----------
Nov  6 03:02:57.641634	INFO	2.4570s INTERNAL_ERR << single[002] (7b948e) >> unknown event: {<nil> <nil> <nil> <nil> <nil> <nil> <nil>}
Nov  6 03:02:57.641699	INFO	2.5923s INCOMPLETE << single[002] (7b948e) >> 
Nov  6 03:02:57.641742	INFO	2.5924s      ERROR << single[002] (7b948e) >> io: read/write on closed pipe
Nov  6 03:02:57.642743	INFO	2.5934s      OTHER << sidecar      >> Nov  6 03:02:57.642405	INFO	resolved route to host	{"host": "testground-redis", "ip": "192.18.0.3"}
Nov  6 03:02:57.643019	INFO	2.5937s      OTHER << sidecar      >> Nov  6 03:02:57.642778	INFO	resolved route to host	{"host": "testground-influxdb", "ip": "192.18.0.4"}
Nov  6 03:02:57.643224	INFO	2.5936s    MESSAGE << sidecar      >> InfluxDB unavailable; no metrics will be dispatched: no InfluxDB URL in $INFLUXDB_URL env var
Nov  6 03:02:57.661809	INFO	2.6125s      OTHER << sidecar      >> Nov  6 03:02:57.661413	INFO	successfully resolved route to host	{"container_id": "7b948e0e3ba2ca4c1923bad0908151e8f1eafc37b6745d066dd4ea31bb632be0"}
Nov  6 03:02:57.662294	INFO	2.6129s      OTHER << sidecar      >> Nov  6 03:02:57.662039	INFO	external routing disabled
Nov  6 03:02:57.662480	INFO	2.6131s      OTHER << sidecar      >> Nov  6 03:02:57.662146	INFO	waiting for all networks to be ready	{"sidecar": true, "run_id": "buibpjdq0l5pqlbfcjn0"}
Nov  6 03:02:57.933759	DEBUG	started container	{"runner": "local:docker", "run_id": "buibpjdq0l5pqlbfcjn0", "id": "80d120a81344a968d368b4d43dab99fa56ce161abc066d7500ed8f4ec04a8eff", "group": "single", "group_index": 0}
Nov  6 03:02:57.934410	INFO	2.8130s INTERNAL_ERR << single[000] (80d120) >> unknown event: {<nil> <nil> <nil> <nil> <nil> <nil> <nil>}
Nov  6 03:02:57.934453	INFO	2.8851s INCOMPLETE << single[000] (80d120) >> 
Nov  6 03:02:57.934486	INFO	2.8851s      ERROR << single[000] (80d120) >> io: read/write on closed pipe

**Comment by nonsense** [comment]
Which test exactly are you executing, and which version of the `go-sdk` is it using?

@sujith2s the latest `master` is not compatible with old versions of the `go-sdk` which seems to be the problem.

Could you try upgrading the `go-sdk` in the test you are using, or let us know which one it is, so that we upgrade it for you?

Alternatively you can try to use the latest stable release of Testground, and not build from source from `master`. We still haven't released `master`, and we are a bit behind on documenting the changes.

**Comment by nonsense** [comment]
@sujith2s I take it you are referencing the `ping` test plan from https://github.com/libp2p/test-plans

If you want to run this test plan with Testground from `master`, you have to upgrade the `testground/go-sdk` package, as it currently is set to `v0.2.3` at https://github.com/libp2p/test-plans/blob/master/ping/go.mod#L11

```
go get github.com/testground/sdk-go@master
```

---

Also it looks like your command is wrong as you are trying to set `--run-cfg log_level=true` - this will result in an error.

After upgrading `testground/sdk-go` to `master`, you can try:

```
testground run single --plan libp2p/ping --testcase ping --builder docker:go --runner local:docker --run-cfg log_level=info --instances=4 --wait
```

Let me know if this helps.

**Comment by sujith2s** [comment]
@nonsense  thank you for your reply and It helps.

yes I was using the  https://github.com/libp2p/test-plans, now I was able to execute the ping test successfully. 

I tried the same for /libp2p/dht test case as well, updated the sdk-go and tried to run the test. 
without updating the sdk-go, i am getting the same error as ping .

cd $TESTGROUND_HOME/plans/libp2p/dht
go get github.com/testground/sdk-go@master

command
-----------
testground run single --plan libp2p/dht --testcase find-peers --builder docker:go --runner local:docker --run-cfg log_level=info --instances=20 --wait

error
------
# github.com/libp2p/test-plans/dht/utils
utils/identifiers.go:28:23: ri.Client.SignalAndWait undefined (type *"github.com/testground/sdk-go/sync".Client is pointer to interface, not interface)
utils/identifiers.go:46:11: ri.Client.MustPublishSubscribe undefined (type *"github.com/testground/sdk-go/sync".Client is pointer to interface, not interface)
utils/staging.go:59:23: s.stager.ri.Client.SignalEntry undefined (type *"github.com/testground/sdk-go/sync".Client is pointer to interface, not interface)
utils/staging.go:64:13: s.stager.ri.RunEnv.RecordMetric undefined (type *"github.com/testground/sdk-go/runtime".RunEnv has no field or method RecordMetric)
utils/staging.go:64:28: undefined: "github.com/testground/sdk-go/runtime".MetricDefinition
utils/staging.go:72:21: s.stager.ri.Client.MustBarrier undefined (type *"github.com/testground/sdk-go/sync".Client is pointer to interface, not interface)
utils/staging.go:73:13: s.stager.ri.RunEnv.RecordMetric undefined (type *"github.com/testground/sdk-go/runtime".RunEnv has no field or method RecordMetric)
utils/staging.go:73:28: undefined: "github.com/testground/sdk-go/runtime".MetricDefinition
utils/staging.go:79:13: s.stager.ri.RunEnv.RecordMetric undefined (type *"github.com/testground/sdk-go/runtime".RunEnv has no field or method RecordMetric)
utils/staging.go:79:28: undefined: "github.com/testground/sdk-go/runtime".MetricDefinition
utils/staging.go:79:28: too many errors

Nov  7 05:53:51.727593	INFO	build failed	{"plan": "dht", "groups": ["single"], "builder": "docker:go", "error": "docker build failed: The command '/bin/sh -c cd ${PLAN_DIR}     && go env -w GOPROXY=\"${GO_PROXY}\"     && CGO_ENABLED=${CgoEnabled} GOOS=linux GOARCH=amd64 go build -o ${PLAN_DIR}/testplan.bin ${BUILD_TAGS} ${TESTPLAN_EXEC_PKG}' returned a non-zero code: 2"}

>>> Result:

docker build failed: The command '/bin/sh -c cd ${PLAN_DIR}     && go env -w GOPROXY="${GO_PROXY}"     && CGO_ENABLED=${CgoEnabled} GOOS=linux GOARCH=amd64 go build -o ${PLAN_DIR}/testplan.bin ${BUILD_TAGS} ${TESTPLAN_EXEC_PKG}' returned a non-zero code: 2


Thanks in advance.

**Comment by nonsense** [comment]
@sujith2s unfortunately the https://github.com/libp2p/test-plans/tree/master/dht is rather outdated - you can try to run it with an older version of Testground, until it is updated.

**Comment by nonsense** [comment]
@sujith2s thanks for raising these issues. I moved this issue to https://github.com/libp2p/test-plans/issues/13 in order to decide on a strategy to keep these plans up-to-date. Let's continue the conversation there!

**Comment by quieoo** [comment]
@nonsense  so i want to know which version of testground should be used to fit with libp2p/dht, for libp2p/ping i have seen it updated and worked well, but as for dht it can not simply change the sdk-go version

**Comment by araskachoi** [comment]
> @nonsense so i want to know which version of testground should be used to fit with libp2p/dht, for libp2p/ping i have seen it updated and worked well, but as for dht it can not simply change the sdk-go version

I would also like to see a working version for this as well!
