### ISSUE TITLE
Hanging at network configuration

### ISSUE THREAD

**Issue by dgrisham** [testground/testground#1175]
#### Version information:
```
$ git log | head -n1
commit 87bd8391a3116cb407446f320481731e20ec24e2
$ uname -a
Linux mainframe 5.9.8-arch1-1 #1 SMP PREEMPT Tue, 10 Nov 2020 22:44:11 +0000 x86_64 GNU/Linux
```

Running arch linux

#### Description:

Hi! When trying to run any `network` related tests, the test hangs at the `MustConfigureNetwork` step. For example, when I run:

```
$ testground run single --plan=network --testcase=traffic-allowed --builder=docker:go --runner=local:docker --instances=1
```

My test hangs at the following step:

```
Nov 15 00:47:24.365250  INFO    build completed {"default_tag": "e62288aeb5fc:latest", "took": "0s"}
Nov 15 00:47:24.415189  INFO    got docker image id     {"image_id": "6dbbcf5e3712"}
Nov 15 00:47:24.476731  INFO    tagging image   {"image_id": "6dbbcf5e3712", "tag": "tg-plan-network:6dbbcf5e3712"}
Nov 15 00:47:24.481009  INFO    build succeeded {"plan": "network", "groups": ["single"], "builder": "docker:go", "artifact": "6dbbcf5e3712"}
Nov 15 00:47:24.481096  INFO    performing healthcheck on runner
Nov 15 00:47:24.497338  INFO    healthcheck: ok
Nov 15 00:47:39.514423  INFO    creating container      {"runner": "local:docker", "run_id": "buo7l76o0u3i8irvgtbg", "name": "tg-network-traffic-allowed-buo7l76o0u3i8irvgtbg-single-0"}
Nov 15 00:47:39.562335  INFO    starting containers     {"runner": "local:docker", "run_id": "buo7l76o0u3i8irvgtbg", "count": 1}
Nov 15 00:47:39.562416  INFO    starting container      {"runner": "local:docker", "run_id": "buo7l76o0u3i8irvgtbg", "id": "4fa0df585363b30fdb062860192402b2f9f9868ff9309731865703c1b653c5a0", "group": "single", "group_index": 0}
Nov 15 00:47:40.010406  INFO    started containers      {"runner": "local:docker", "run_id": "buo7l76o0u3i8irvgtbg", "count": 1}
Nov 15 00:47:40.011633  INFO    0.4424s    MESSAGE << single[000] (4fa0df) >> registering default http handler at: http://[::]:6060/ (pprof: http://[::]:6060/debug/pprof/)
Nov 15 00:47:40.011674  INFO    0.4493s      OTHER << sidecar      >> Nov 15 00:47:40.011450    INFO    resolved route to host  {"host": "testground-redis", "ip": "192.18.0.3"}
Nov 15 00:47:40.011706  INFO    0.4425s      START << single[000] (4fa0df) >> {"plan":"network","case":"traffic-allowed","run":"buo7l76o0u3i8irvgtbg","outputs_path":"/outputs","instances":1,"group":"single","group_instances":1,"network":"16.14.0.0/16","start_time":"0001-01-01T00:00:00Z"}
Nov 15 00:47:40.011746  INFO    0.4426s    MESSAGE << single[000] (4fa0df) >> before sync.MustBoundClient
Nov 15 00:47:40.011781  INFO    0.4432s    MESSAGE << single[000] (4fa0df) >> before netclient.MustWaitNetworkInitialized
Nov 15 00:47:40.011790  INFO    0.4494s      OTHER << sidecar      >> Nov 15 00:47:40.011657    INFO    resolved route to host  {"host": "testground-influxdb", "ip": "192.18.0.4"}
Nov 15 00:47:40.011965  INFO    0.4494s INTERNAL_ERR << sidecar      >> unknown event: {<nil> <nil> <nil> <nil> <nil> <nil> <nil>}
Nov 15 00:47:40.011983  INFO    0.4496s INCOMPLETE << sidecar      >> 
Nov 15 00:47:41.006386  INFO    1.4437s    MESSAGE << single[000] (4fa0df) >> network initialisation successful
Nov 15 00:47:41.006463  INFO    1.4438s    MESSAGE << single[000] (4fa0df) >> before netclient.MustConfigureNetwork
```

I originally noticed this when trying to port [this bitswap test](https://github.com/ipfs/test-plans/blob/master/bitswap-tuning/test/transfer.go) to version `0.2.6` of the testground go sdk. Once I updated it, I noticed the hanging, then proceeded to test the default `ping-pong` and `traffic-allowed` tests. It seems like it must be stopping at [this line](https://github.com/testground/sdk-go/blob/master/network/client.go#L101), but that's the most I've figured out so far.

I've tried killing the sidecar/other containers and restarting them, but the issue persists. Not sure if this is something on my end or a bug, any help would be appreciated!

**Comment by nonsense** [comment]
@dgrisham this is most probably a bug - I think the testplans are not compatible with testground master branch because they currently use an outdated sdk-go.

You could try upgrading the testground/sdk-go library to master in the testplan.

Alternatively, try using a stable Testground release. 

I will look into this thoroughly on Monday.

**Comment by dgrisham** [comment]
Gotcha, that makes sense. I tried switching to the same sdk-go as `testground/master` is using, but I had the same issue. Tried switching to `tags/v0.5.3`, but ran into [this issue](https://github.com/testground/testground/issues/1133). Once I switched to [the commit that fixed that issue](https://github.com/testground/testground/commit/8d672014fbbb816cae8bf1db52054ca6ac198b31) and had testground use the corresponding sdk-go (0.2.4), it worked!

**Comment by nonsense** [comment]
@dgrisham I had some time to look into this, and I can't reproduce the problem you report on the test plan run:

```
$ testground run single --plan=network --testcase=traffic-allowed --builder=docker:go --runner=local:docker --instances=1
```

---

Could you confirm that you run `make` after checking out Testground at version `87bd8391a3116cb407446f320481731e20ec24e2` and then make sure that you remove all docker containers on your machine? It is possible that you are running an outdated version of the sidecar. You can remove all running containers with `docker ps -a -q | xargs docker rm -f`.

I am also puzzled by the errors on your side, because the network test plans are also run on CI (you can find them under `make test-integ-local-docker` in the `Makefile`).

---

I've submitted a PR that simplifies a bit the test plan (https://github.com/testground/testground/pull/1177), but in any case the version on `master` should work as well.

**Comment by nonsense** [comment]
The fact that I see the following ERR in your output, makes me think that you are probably running an outdated test plan. Did you symlink the plan from your $TESTGROUND_HOME or you just copied it over?

```
Nov 15 00:47:40.011965  INFO    0.4494s INTERNAL_ERR << sidecar      >> unknown event: {<nil> <nil> <nil> <nil> <nil> <nil> <nil>}
```

**Comment by dgrisham** [comment]
@nonsense Removing the running docker containers worked! The `ping-pong` test works now, my updated Bitswap one doesn't but that's probably something on my end. Thanks!

**Comment by nonsense** [comment]
@dgrisham I haven't tried the `bitswap` test - will look into it. Since the removing of the docker containers worked, it means that probably there was a sidecar running that was outdated! Thanks for the update.

**Comment by dgrisham** [comment]
@nonsense no worries -- the bitswap test hosted by PL is using an older version of Testground, I have a local version that I tried updating to use the newer SDK. If I run into anything that I can't figure out I may ping for some advice haha

**Comment by dgrisham** [comment]
Update -- the bitswap-tuning test works great, it failed that day for some reason but has been good since :ok_hand:

**Comment by hannahhoward** [comment]
@nonsense really glad this was here cause I ran into it as well. Removing the containers fixed my problems -- I wonder about documenting that fix as well, or even better, identifying when a container is out of date has some other problem.

**Comment by DANIEL-FONT-CEO** [comment]
👍 I'm going to keep Working on my Code 🙏
