### ISSUE TITLE
Proposal: Use go.mod for the build step. 

### ISSUE THREAD

**Issue by daviddias** [testground/testground#118]
> Notes from a convo with @raulk 

Currently, the docker builder blasts the existing go.mod and fetches all the latest released versions of every module. This is done in order to make sure that Test Ground always tests the latest code, however it creates the problem for tests that rely on code that hasn't been released it (e.g. the issue with go-libp2p-kad-dht/opts).

testground cli has an option `--dep=<dep url>=<version to be used>` to specify an alternative version of a dep. The issue that remains is that this knowledge (of which versions need to be switched) stays on the original developer's brain and not in a versioned dep lock file.

We need:

- A way to communicate  the dep versions that the test needs in order to run (equivalent to package-lock.json). This is a wish for semver in go.mod 🙏🏽 but that isn't yet a thing.
- Set as a default behavior to always use latest in Test Ground with the exception to the list defined above.

**Comment by jimpick** [comment]
I think this might need a "design blueprint" pass ... @raulk?

**Comment by raulk** [comment]
This was already implemented a long while ago 🎉
