### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by chriskarapapas** [testground/testground#1184]
Hello! 
After installing on Ubuntu 20.04 
and  running “testground daemon” as suggested  i get a “testground: command not found.”.

The make install procedure ended without errors.
Thanks

**Comment by nonsense** [comment]
@chriskarapapas make sure your $GOPATH/bin is in your $PATH. Ubuntu searches the $PATH when you try to run an executable, and it seems like it can't find it there. Make sure that $GOPATH is defined if you downloaded and compiled the source, make sure the resulting binary is in your `$PATH`. Maybe this article will help: https://www.digitalocean.com/community/tutorials/understanding-the-gopath

**Comment by nonsense** [comment]
@chriskarapapas let me know if you have any other problems, but this appears to be a user issue, and not a problem with Testground.
