### ISSUE TITLE
Make InfluxDB metrics pushing optional and text file

### ISSUE THREAD

**Issue by dgrisham** [testground/testground#1188]
I'm running a custom Bitswap test where I record every peer's ledger values every millisecond. This generates a lot of data that I then post-process from the test users' `results.out` files. However, it seems to also generates enough data to cause an error at the end of the test when trying to load everything into InfluxDB.

Example output:

```
Jan 23 20:07:48.252064  INFO    21.0950s    MESSAGE << single[001] >> failed to send batch to InfluxDB; attempt 4; err: {"error":"Request Entity Too Large"}

Jan 23 20:07:48.252130  INFO    21.0951s    MESSAGE << single[001] >> influxdb: failed to upload 366998 points; err: All attempts fail:
#1: {"error":"Request Entity Too Large"}

#2: {"error":"Request Entity Too Large"}

#3: {"error":"Request Entity Too Large"}

#4: {"error":"Request Entity Too Large"}

#5: {"error":"Request Entity Too Large"}
```

My question is: can I disable InfluxDB entirely, while still retaining the `results.out`/other text files? I haven't seen an option for that, the most relevant code I've found that might point to what I want is [here](https://github.com/testground/sdk-go/blob/master/runtime/metrics.go#L39) (though `InfluxBatching` seems hardcoded to `true` in `sdk-go`).

Not sure if this is a feature request or docs issue (or if I'm just missing something obvious). Let me know if I can provide any more detail!

**Comment by hacdias** [comment]
I will take over this issue and #1253. The tasks here:

- [ ] Allow to completely disable InfluxDB metrics pushing
- [ ] Only emit metrics to text file
