### ISSUE TITLE
Timeout errors connecting to InfluxDB

### ISSUE THREAD

**Issue by acruikshank** [testground/testground#1189]
#### Version information:

commit f3e580923ab54af9e0d0d2e08e840839ec2b64b9

MacBook Pro
2.9 GHz 6-Core Intel Core i9
OS X 10.15.7

#### Description:

I am trying to run local:docker compositions in the http://github.com/protocol/beyond-bitswap repo. For example: https://github.com/protocol/beyond-bitswap/blob/master/RFC/rfcBBL102/baseline.toml. Every run starts emitting: 
```
failed to send batch to InfluxDB; attempt 0; err: Post "http://testground-influxdb:8086/write?consistency=&db=testground&precision=ns&rp=": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
after ~1 minute. Before the errors I sometimes get some metrics written to results.out beforehand, but never get any after. The parameters of the test run affect when the errors start a bit, but the failure is consistent.

I have noticed a few 500 errors (among hundreds of successful requests) in the InfluxDB logs, but the timeout issue occurs even when these errors are not present. Unfortunately, there is no additional info in the logs to suggest what is causing the 500.

**Comment by acruikshank** [comment]
Worth noting that I can run other testground tests (from different repos) on this machine using the same testground binary for several minutes without getting an InfluxDB timeout.

**Comment by raulk** [comment]
@acruikshank could you try:

1. updating the sdk-go dependency on the test plan to the latest release
2. `testground terminate --runner local:docker`
3. stopping the daemon
3. rebasing your testground checkout on origin/master
4. rebuilding the sidecar: `make`
5. starting the daemon

---

@nonsense this could be an outdated SDK, or an issue with the sidecar.

---

@acruikshank do you _actually_ need to analyze these datapoints in InfluxDB? If, not we could add an option to opt-out of InfluxDB. It does not solve the stability problem, but at least it unblocks you.

**Comment by acruikshank** [comment]
@raulk I followed these steps. It didn't fix the problem but I did notice an error at the very beginning of the run I hadn't before:
```
<< sidecar      >> InfluxDB unavailable; no metrics will be dispatched: no InfluxDB URL in $INFLUXDB_URL env var
```
Unfortunately I can't confirm whether this was always there or not. 

I did try to run another test after discovering this. I do see see this error many times, but this run actually worked. I have metrics in the node's results.out. So I'm still pretty confused. Especially since the env var seems to be hardcoded here: https://github.com/testground/testground/blob/f3e580923ab54af9e0d0d2e08e840839ec2b64b9/pkg/runner/local_docker.go#L287

**Comment by nonsense** [comment]
1. Outdated SDK

> @nonsense this could be an outdated SDK, or an issue with the sidecar.

This certainly seems like the problem.

2. Incorrect log line
```
<< sidecar      >> InfluxDB unavailable; no metrics will be dispatched: no InfluxDB URL in $INFLUXDB_URL env var
```

@acruikshank this appears to be a red-herring. The sidecar doesn't need InfluxDB env var, it is not emitting metrics, the testplan containers are emitting metrics. I will see about fixing this log line.

3. I tried running Testground from master and the `RFC/rfcBBL102/baseline.toml` composition, and I am getting metrics in InfluxDB on my end, which makes me think that this is some misconfiguration that is happening locally. Here are a few ideas on how to fix:

------

a) Docker version: @acruikshank please make sure that you are running an up-to-date Docker for Mac.

b) Remove existing docker containers, provided that you don't care about their state and you are not running any important applications in Docker - `docker ps -a -q | xargs docker rm -f` - this will remove all containers

c) Restart `testground daemon`

d) Run testplan `testground run composition -f RFC/rfcBBL102/baseline.toml`

e) Confirm that you are getting metrics in InfluxDB:

`docker exec -it testground-influxdb influx`
`USE testground`
`SHOW measurements`

---

For reference I am attaching the logs from my end.
[c09um96vvhfn1ik69g9g.txt](https://github.com/testground/testground/files/5893511/c09um96vvhfn1ik69g9g.txt)

**Comment by nonsense** [comment]
After debugging this with @acruikshank , we found out that:
1. Docker for Mac has low memory resources allocated (2GB total). This might be enough for 20-25 containers, but it is on the limit.
2. We noticed that `.env.toml` doesn't have any settings for `local:docker`, so no `ulimits` were being sent to the individual containers, and they were most probably inheriting low open files limit.

This was visible when we tried to attach to the `testground-influxdb` container, which was impossible.

---

So as a resolution we bumped ulimits on the host, as well as memory resources for Docker for Mac, but this issue is most probably triggered by exhausting connections on the host. I added an issue so that we document this better within Testground, because I believe we could do a better job at this - https://github.com/testground/testground/issues/1190

**Comment by acruikshank** [comment]
Thanks @nonsense for helping out with this. I'm pretty convinced it was the low memory allocation to Docker that caused the problem with InfluxDB. At any rate, the tests seem to be running great now with 16Gb, so I'm going to close this.
