### ISSUE TITLE
Consider adding support for interpolating env vars in composition files

### ISSUE THREAD

**Issue by nonsense** [testground/testground#1197]
It'd be nice if we can have env vars in composition files - for example when needing to specify different Docker images (`artifacts` in Testground lingo) at various places in composition.toml , and have CI easily replace two versions (i.e. `current` and `release`).

That should be fairly simple to achieve for example using https://github.com/spf13/viper or something similar to read in the the composition and replace the ENV vars.

**Comment by raulk** [comment]
Ah, this is about variable interpolation in compositions, right? The simplest solution would be to treat the composition file as a Go template, and map the environment variable map into a `.Env` binding, so you can do `{{.Env["VARIABLE"]}}`. WDYT, @nonsense?

**Comment by nonsense** [comment]
> Ah, this is about variable interpolation in compositions, right?

Yes.

> The simplest solution would be to treat the composition file as a Go template, and map the environment variable map into a .Env binding, so you can do {{.Env["VARIABLE"]}}.

That's one solution.

In the past I've used .toml files which just include `key="$ENVNAME"` and parse that with tools like `viper`.

Both options are good.

**Comment by hacdias** [comment]
Quickly jumping here: I can probably implement this as soon as #1187 is finished.

Advantages for Go template: native, no more deps; can be used to add other data if needed.
Disadvantages for Go template: more annoying syntax.

Advantage for Viper: easier syntax.
Disadvantage: only for env vars (right?) and additional dependency.
