### ISSUE TITLE
testground cannot schedule job when there is a built artefact with the same name in the testplan directory

### ISSUE THREAD

**Issue by nonsense** [testground/testground#1198]
#### Version information:
`f3e5809`

#### Description:
If you try to compile a test plan and then schedule it to the `testground daemon`, the testground client errors out with:

```
➜  storm testground run composition -f ./compositions/storm-goproxy-remote.toml
Feb 24 12:39:01.989482  INFO    using home directory: /Users/nonsense/tghome
Feb 24 12:39:01.992017  INFO    .env.toml loaded from: /Users/nonsense/tghome/.env.toml
Feb 24 12:39:01.992040  INFO    testground client initialized   {"addr": "https://ci.testground.ipfs.team"}
invalid character '<' looking for beginning of value
```

This is most probably due to the fact that there is a binary with the same name as the test plan in the directory of the test plan - in the case of this example, test plan and test case named `storm` and a built binary named `storm` - probably some kind of name collision is happening when sending the test plan to the daemon.

**Comment by nonsense** [comment]
Even having other folders in the Testground context can trigger that, not just a file named as the test plan.

**Comment by hacdias** [comment]
Hey @nonsense!

I just trying to reproduce the error, unsuccessfully, what I tried:

- Create binary files (just using `go build`) with the same name of the test plan and test case.
- Create directories with the same name of the test plans and test cases.

I tested with local runners and `single` (not `compositions`).. Both `master` and `f3e5809`. Looking at your logs, it seems to fail while queueing, so I feel there's two options:

- It only affects `k8s` as queuing as we need to send the data "up".
- It only affects compositions, even if they're run locally.

I will keep investigating.

**Comment by hacdias** [comment]
After more investigation, it does seem that the issue is not Testground itself, but the nginx configuration. I tried many things:

- I created a directory. Did not fail.
- I created an executable file. Did not fail.
- I added a large binary. It fails.

Then I decided to print the actual output response from the client, which is:

```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

The binary does not need to have the same name of the test plan:

```bash
~ ☁️  (eu-west-2) ✖ go build
~ ☁️  (eu-west-2) ❯ mv network test
~ ☁️  (eu-west-2) ❯ tgr s -r cluster:k8s -b docker:go -p network -t network -i 2
Jun 19 06:12:51.493083	INFO	created a synthetic composition file for this job; all instances will run under singleton group "single"
Jun 19 06:12:51.493267	INFO	using home directory: /Users/henriquedias/testground
Jun 19 06:12:51.493821	INFO	.env.toml loaded from: /Users/henriquedias/testground/.env.toml
Jun 19 06:12:51.493834	INFO	testground client initialized	{"addr": "https://ci.testground.ipfs.team"}
<nil>
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

@nonsense I guess I can't fix this by myself, so I would ask you to take a look at the `client_max_body_size` option in nginx.
