### ISSUE TITLE
Error on Parameters and test cases Docs

### ISSUE THREAD

**Issue by pedroaston** [testground/testground#1221]
The main.go function presented on the bellow page was giving me compile errors. I then made one similar to the one at testground/plans/examples and all went well. 

Errors were:
- undefined functions at runtime package (InvokeMap and TestCaseFn)
- once switched to package run i add this ... 
./main.go:9:44: cannot use map[string]func(*"github.com/testground/sdk-go/runtime".RunEnv) error{...} (type map[string]func(*"github.com/testground/sdk-go/runtime".RunEnv) error) as type map[string]interface {} in argument to run.InvokeMap

Url >> https://docs.testground.ai/writing-test-plans/paramaters-and-testcases

Don't know if this is a real problem or just my mine, anyway here is the tip.

PS: Same package problem at Communication between instances.

**Comment by daonb** [comment]
I tested it and indeed it fails. I fixed it by changing line 9 to:

```
    runtime.InvokeMap(map[string]interface{}{
 ```

Not sure how to update the docs.

**Comment by hacdias** [comment]
Thank you for noticing this. I updated it for the `master` version. Please note that when you open the docs website, you get the documentation for the latest released version, which was 0.5.3. There's been a lot of updated between that and the current `master` code and the documentation may not be 100% up to date.
