### ISSUE TITLE
All peers fail to connect with i/o timeout after 46 instances on Linux with local:docker

### ISSUE THREAD

**Issue by tchardin** [testground/testground#1225]
#### Version information:

`3da7c61944ad273856c45d6d90a20eaf9e0dfdb6`

Ubuntu AMD Ryzen 9 3900XT 12-Core Processor - 64GiB DDR4
#### Description:

When running `ping` test case from libp2p [test-plans](https://github.com/nonsense/test-plans/tree/upgrade-libraries) with `local:docker` the runner seems to hit some type of limit and all peers fail to connect and print: `<< low-latency[049] (06ed86) >> failed to dial Qmb19y4eaKyR8gXRqNnv9KeBbHte5VnzX92YVhVVheh5me: all dials failed * [/ip4/16.3.0.46/tcp/40445] dial tcp4 0.0.0.0:41557->16.3.0.46:40445: i/o timeout`. 
We have tried with some AWS `C5.2xlarge` machines as well. Also tried raising most relevant `ulimit` parameters without success.

**Comment by raulk** [comment]
This turned out to be a host OS configuration issue. Explained here for posterity: https://github.com/testground/testground/discussions/1240
