### ISSUE TITLE
testground-redis container not starting: can't open nf_conntrack_max for writing

### ISSUE THREAD

**Issue by dgrisham** [testground/testground#1230]
#### Version information:

```
$ git log | head -n1      
commit b8e1eeddb7658e405109d2f26f2f63bb6973ece5
```

Arch Linux, x64.

#### Description:

I've been running tests branched off of the beyond-bitswap repo, but I believe this error is test-independent.

When I run the test, I get an error when testground tries to spin up the Redis container:

```
{
  "container_name": "testground-redis",
  "error": "Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: write sysctl key net.netfilter.nf_conntrack_max: open /proc/sys/net/netfilter/nf_conntrack_max: permission denied: unknown"
}
```

and:

```
May 15 22:28:12.758409  ERROR   doRun returned err
{"err": "healthcheck fixes failed; aborting: Checks:
    - local-outputs-dir: failed; directory does not exist. can recreate.
    - control-network: ok; network exists.
    - local-grafana: failed; container state: exited
    - local-redis: failed; container state: exited
    - local-influxdb: failed; container state: exited
    - sidecar-container: failed; container state: exited
Fixes:
    - local-outputs-dir: ok; directory created successfully.
    - control-network: unnecessary;
    - local-grafana: ok; container created.
    - local-redis: failed; failed to start container.
    - local-influxdb: ok; container created.
    - sidecar-container: ok; container created."
}
```

I'd been successfully running tests prior to this. I'm not sure what changed. I don't quite recall if I got this error before upgrading to the most recent testground commit or if I received the error from an old branch then updated to test on the newest, but I'll try downgrading to see if the error was recently introduced.

**Comment by dgrisham** [comment]
Update: this issue persists for me on previous `testground` commits as well. Starting to think it's to do with docker or some other dependency.

**Comment by dgrisham** [comment]
So, I tried updating the `net.netfilter.nf_conntrack_max` value that's set [here](https://github.com/testground/testground/blob/master/pkg/runner/local_common.go#L67) by renaming it to `net.nf_conntrack_max`. I *didn't* get an error like first error in the OP where it said

```
write sysctl key net.netfilter.nf_conntrack_max: open /proc/sys/net/netfilter/nf_conntrack_max: permission denied: unknown
```

but I *did* still get the second error saying `local-redis: failed; failed to start container.` So I tried removing the value completely, and now everything is running again. I'm guessing changing that value isn't particularly consequential aside from maybe preserving system resources?

Not sure what the follow up here is, my issue is solved for the time being though.

**Comment by hacdias** [comment]
Hello @dgrisham,

That is quite odd indeed. I've never seen that error before. We change this setting to allow the Redis container to receive lots of connections at once. I don't see how that would create a permission denied error as this is a kernel parameter of the container, not of the host OS.

Do you know if anything changed in your system when the error started happing? New users? Some OS update? Some permissions changed? Docker updates/configuration changes?

**Comment by dgrisham** [comment]
Probably -- I've been keeping things updated pretty regularly, and I'm on Arch so I may have some changes that are upstream relative to other operating systems (I've seen `containerd` update a few times recently, not sure how relevant that is to this). Agreed that it seems strange that this is happening when that'd be a configuration value in the Redis container, so perhaps some other bug specific to my setup is happening.

**Comment by hacdias** [comment]
Yeah, unfortunately I don't think I can help with this information only... Hmm... @nonsense have you ever seen something similar happen?

**Comment by dgrisham** [comment]
@pedroaston I ended up just commenting out the line that's setting that value in the code that I mentioned before ([here](https://github.com/testground/testground/blob/master/pkg/runner/local_common.go#L67)) and was running everything that way for awhile. I'm sure there's a better solution but I didn't seem to run into any issues for my use case.

**Comment by hacdias** [comment]
This may be farfetched, but is there any way for you to see if there's **any** version differences on the previous and the new VM (kernel, software, etc...)? @pedroaston

**Comment by pedroaston** [comment]
@dgrisham your fix also seems to be working in my testground environment. Thanks!

**Comment by pedroaston** [comment]
@hacdias sometimes when some instances crashed on my test runs, on the next one, all instances were stuck with timeout when trying to connect. By the way I'm using as base of the test the libp2p dht test plan.To solve this I had to prune the containers and restart the guest and host systems.  
In terms of updates the only update I may have done was a ubuntu upgrade on the VM, but I'm not sure. Either way here are my current VM specs:
- kernel: 5.8.0-59-generic
- ubuntu: 20.04.2 LTS 64-bit

**Comment by chriskarapapas** [comment]
Hello guys,
i continue at this post as i think the error is similar. If not i will make a new one!

`ERROR	starting container failed	{"container_name": "testground-redis", "container_name": "testground-redis", "error": "Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: write sysctl key net.netfilter.nf_conntrack_max: open /proc/sys/net/netfilter/nf_conntrack_max: permission denied: unknown"}
Jul 11 16:08:06.423961	INFO	container isn't running; starting	{"container_name": "testground-influxdb"}
Jul 11 16:08:06.838747	ERROR	doRun returned err	{"err": "healthcheck fixes failed; aborting:\nChecks:\n- local-outputs-dir: ok; directory exists.\n- control-network: ok; network exists.\n- local-grafana: failed; container state: exited\n- local-redis: failed; container state: created\n- local-influxdb: failed; container state: exited\n- sidecar-container: ok; container state: running\nFixes:\n- local-outputs-dir: unnecessary; \n- control-network: unnecessary; \n- local-grafana: ok; container created.\n- local-redis: failed; failed to start container.\n- local-influxdb: ok; container created.\n- sidecar-container: unnecessary; \n"}
Jul 11 16:08:06.839362	INFO	worker completed task	{"worker_id": 0, "task_id": "c3lheovt090d3upaibjg"}
Jul 11 16:09:28.068922	WARN	healthcheck error	{"req_id": "a6c09078", "err": "unknown runner: docker"}
Jul 11 16:09:35.743229	INFO	checking runner: local:docker	{"req_id": "38a0cc81"}
Jul 11 16:09:35.747956	INFO	container isn't running; starting	{"req_id": "38a0cc81", "container_name": "testground-redis"}
Jul 11 16:09:36.768128	ERROR	starting container failed	{"req_id": "38a0cc81", "container_name": "testground-redis", "container_name": "testground-redis", "error": "Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: write sysctl key net.netfilter.nf_conntrack_max: open /proc/sys/net/netfilter/nf_conntrack_max: permission denied: unknown"}
`

I have also made a healthcheck and the result is that  ' local-redis: failed; failed to start container.'

**Comment by chriskarapapas** [comment]
This solution seems to work for me for now
` if [[ $(docker ps -q) ]] ; then docker kill $(docker ps -q) ; else true ; fi && if [[ $(docker ps -aq) ]] ; then docker rm $(docker ps -aq) ; else true ; fi ; sudo service docker restart`
 borrowed from [here](https://stackoverflow.com/questions/48586868/oci-runtime-create-failed-container-linux-go296-no-such-file-or-directory/48587685)

**Comment by ihlec** [comment]
The solution for me was to downgrade Docker to version 1:20.10.5-1

**Comment by daonb** [comment]
I'm getting this on a fresh install of Ubuntu server. It could be a result of a change in Linux kernel 5.12.2:


commit 671c54ea8c7ff47bd88444f3fffb65bf9799ce43
Author: Jonathon Reinhart <jonathon.reinhart@gmail.com>
Date:   Mon Apr 12 00:24:53 2021 -0400

    netfilter: conntrack: Make global sysctls readonly in non-init netns
    
    commit 2671fa4dc0109d3fb581bc3078fdf17b5d9080f6 upstream.
    
    These sysctls point to global variables:
    - NF_SYSCTL_CT_MAX (&nf_conntrack_max)
    - NF_SYSCTL_CT_EXPECT_MAX (&nf_ct_expect_max)
    - NF_SYSCTL_CT_BUCKETS (&nf_conntrack_htable_size_user)
    
    Because their data pointers are not updated to point to per-netns
    structures, they must be marked read-only in a non-init_net ns.
    Otherwise, changes in any net namespace are reflected in (leaked into)
    all other net namespaces. This problem has existed since the
    introduction of net namespaces.
    
    The current logic marks them read-only only if the net namespace is
    owned by an unprivileged user (other than init_user_ns).
    
    Commit d0febd81ae77 ("netfilter: conntrack: re-visit sysctls in
    unprivileged namespaces") "exposes all sysctls even if the namespace is
    unpriviliged." Since we need to mark them readonly in any case, we can
    forego the unprivileged user check altogether.
    
    Fixes: d0febd81ae77 ("netfilter: conntrack: re-visit sysctls in unprivileged namespaces")
    Signed-off-by: Jonathon Reinhart <Jonathon.Reinhart@gmail.com>
    Signed-off-by: David S. Miller <davem@davemloft.net>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

**Comment by hacdias** [comment]
@daonb that seems to be it as it says they're read-only now. I also just noticed we're using a very old Docker API package. However, I don't think that'd influence in anything since Docker itself is performing the container creation operation.

It's also interesting how there's no issue on https://github.com/docker/docker. I will probably work on updating the dependencies for 0.6.0. Perhaps it will fix it. If it doesn't, I'll open an issue on docker repo.

**Comment by nikosft** [comment]
I also confirm the issue.
```
uname -a
Linux mmlab-21 5.4.0-80-generic #90~18.04.1-Ubuntu SMP Tue Jul 13 19:40:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

docker --version
Docker version 20.10.5, build 55c4c88
```

What worked for me was commenting out line 67 in pkg/runner/local_common.go as @pedroaston  mentioned and re-installing everything.

@hacdias since the issue is cause by this line https://github.com/testground/testground/blob/8e76ab86474215293d647a9d03927cdde4948b61/pkg/runner/local_common.go#L67 I guess it is not a docker issue.

**Comment by guseggert** [comment]
Docker's documentation says:

> Not all sysctls are namespaced. Docker does not support changing sysctls inside of a container that also modify the host system.

This sysctl does modify the host system, so I think the only reasonable fix for Docker would be to disallow it, which wouldn't fix the issue here. If this setting is really necessary then perhaps it should be set outside of the container by the user. For Mac users, we could follow similar steps as [what Elasticsearch has documented](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/docker.html#docker-cli-run-prod-mode). 

Also, for me this means running testground with an older kernel would have a side-effect of reducing my `nf_conntrack_max` system-wide by over 50%:

```
$ sysctl net.netfilter.nf_conntrack_max
net.netfilter.nf_conntrack_max = 262144
```

**Comment by ihlec** [comment]
@daonb I switched Kernels on my Manjaro-system prior to downgrading the Docker Package.
Switching to LTS and older Kernels didn't fix the issue for me.

**Comment by hacdias** [comment]
Thanks for all the research that you all did. It seems the best solution would be to remove that line from the code **and** add in the documentation the need to configure the host system accordingly (eg [Elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/docker.html#docker-cli-run-prod-mode)).

/cc @nonsense
