### ISSUE TITLE
Testground using an older version of go

### ISSUE THREAD

**Issue by pedroaston** [testground/testground#1231]
#### Version:
Latest one at the time of writing

#### Description:
I've been using testground without any problem so far but now when i use one version of my program that uses a *time function from go 1.15 it is having the problem shown on the image below. I always had both at go.mod and the manifest.toml the go version 1.16, and don't know if this has to do with any install default of testground. Don't know if i am missing something
![Captura de ecrã de 2021-05-18 06-39-08](https://user-images.githubusercontent.com/36762762/118662186-aa066f00-b7a4-11eb-8de8-125cba3de1f3.png)

**Comment by hacdias** [comment]
Hey @pedroaston!

By defalt

**Comment by hacdias** [comment]
Hey @pedroaston!

By default, `docker:go`'s builder default image is `golang:1.14.4-buster`. If you need a newer version, you can customize your `manifest.toml` like this:

```
[builders."docker:go"]
build_base_image = "golang:1.16-buster"
```

Let me know if that worked!

---

On other note, I will also work on upgrading Testground Go version and defaults to Go 1.16.

**Comment by pedroaston** [comment]
That solved it @hacdias . Thanks for the tip.
