### ISSUE TITLE
add functionality to testground to periodically emit goroutine dumps via the sdk-go

### ISSUE THREAD

**Issue by nonsense** [testground/testground#1232]
At the moment most of the failures we encounters with Testground testplans on TaaS is that they timeout for various reasons, due to barrier not being hit, because of various bugs.

It'd be very helpful if we can add a parameters to the compositions files and request the `sdk-go` to trigger goroutine dumps every N seconds, so that we can review goroutine dumps for test runs that timed-out.

**Comment by hacdias** [comment]
Just to clarify: we're talking about stack dumps, right? That way we can see which point in the code we're at. I will take care of this on Saturday.

**Comment by raulk** [comment]
This feature is already present since https://github.com/testground/sdk-go/pull/38 and https://github.com/testground/testground/pull/1209. We should deduplicate what has been done here!
