### ISSUE TITLE
Harden Testground security on TaaS

### ISSUE THREAD

**Issue by nonsense** [testground/testground#1237]
So far we've been very liberal with security on TaaS, which has worked fine.

We should introduce proper auth tokens, so that we know which jobs are started by which actors/users and have an easier way of tracking the users of the system.

---

For example at the moment some of the users of Testground as misconfigured and we do not get information about who started a given task:

<img width="1652" alt="Screenshot 2021-05-27 at 10 49 16" src="https://user-images.githubusercontent.com/50459/119795992-4503f500-bed9-11eb-9282-90806cc1ff9a.png">

**Comment by BigLep** [comment]
Duplicate of https://github.com/testground/testground/issues/1294
