### ISSUE TITLE
make influxdb metrics pushing optional

### ISSUE THREAD

**Issue by nonsense** [testground/testground#1253]
At the moment stats are not used on TaaS, but we still try to push metrics to InfluxDB as part of every test plan, which results in a lot of irrelevant error logs.

We should make it possible to optionally enable/disable stats/metrics as part of any testplan - at the moment the Testground SDK is always starting up the metrics reporter.

**Comment by nikosft** [comment]
This is also related  to #1188

**Comment by hacdias** [comment]
Closing in favor of #1188
