### ISSUE TITLE
Add output direcory to .dockerignore

### ISSUE THREAD

**Issue by nikosft** [testground/testground#1254]
`docker build` command tries to copy the entire `testground` directory in newly created images, including the output directory. However there can be cases where the output directory is not empty (e.g., trying to re-install testground). For example in my case the output directory was over 100GB and `docker build` took ages to complete.

**Comment by hacdias** [comment]
Hey @nikosft - I've never seen an `output` directory being created on the `testground` directory. I just run `make install` and no new files were created on the git repository. How are doing to the installation? Are you collecting the test outputs to the repository itself? I'm up to add the directory to the `.dockerignore` file, but I need to understand how it is being generated in first place.

**Comment by nikosft** [comment]
Sorry, I meant `data/outputs` directory

**Comment by hacdias** [comment]
`data/outputs` is on `~/testground` (aka `TESTGROUND_HOME`). That is not supposed to be included on the Testground Docker image. Do you have testground cloned in your home directory? `TESTGROUND_HOME` is not supposed to be the same place as the testground code repository.

**Comment by nikosft** [comment]
Yeap, testground is cloned in my home directory. 

> TESTGROUND_HOME is not supposed to be the same place as the testground code repository.

This was not obvious to me. Moreover, I think it is reasonable that somebody clones a directory in the home directory. IMHO this should be included explicitly in README, or it should be checked during install, or install should create another directory e.g., testground-bin.

**Comment by hacdias** [comment]
I will leave this issue open so I can add this to the docs to clarify.

**Comment by hacdias** [comment]
I added that information to the docs: https://docs.testground.ai/v/master/concepts-and-architecture/test-structure#where-do-test-plans-live
