### ISSUE TITLE
Runner flag is missing for collect command

### ISSUE THREAD

**Issue by Bidon15** [testground/testground#1274]
#### Version information:

git rev-parse --verify HEAD
0b997a15b2df79356d262e2afe69f85fadd08545

Setup 1 - MBP 2018: 
- Intel x86 64bit
- OS Big Sur 11.6
- Go ver: 1.17

Setup 2 - Digital Ocean Droplet : 
- x86 64bit
- Ubuntu 20.04.2 LTS
- Go ver: 1.17
#### Description:

Pre-Reqs:

- Cloned testground repo
- Installation done via `make install`

Steps to reproduce: 

1. Open terminal window
2. Execute `testground daemon`
3. Open another terminal window
4. Execute `testground plan import --from ./plans/network`
5. Execute `testground run single --plan=network --testcase=ping-pong  --builder=docker:go --runner=local:docker --instances=2`
6. Execute `testground collect --runer=local:docker <$run_queue_ID>`

Expected result: 
- logs are archived to  `<$run_queue_ID>.tgz` file

Actual result:
- Error is thrown: `Incorrect Usage: flag provided but not defined: -runer`

Note:

- Strangely, but `-r` shorthand version is working as expected

**Comment by brdji** [comment]
I think the issue is a small typo in the command in step 6.
It should be `runner`, not `runer`.

**Comment by Bidon15** [comment]
Thanks for bumping this issue. I totally forgot about it(found the mistypo myself, but didn't close the issue) 
Closing as irrelevant
