### ISSUE TITLE
empty results for executed test-plan

### ISSUE THREAD

**Issue by Bidon15** [testground/testground#1275]
#### Version information:

git rev-parse --verify HEAD
0b997a15b2df79356d262e2afe69f85fadd08545

Setup 1 - MBP 2018: 
- Intel x86 64bit
- OS Big Sur 11.6
- Go ver: 1.17

Setup 2 - Digital Ocean Droplet : 
- x86 64bit
- Ubuntu 20.04.2 LTS
- Go ver: 1.17

#### Description:

Pre-Reqs:

- Cloned testground repo
- Installation done via `make install`

Steps to reproduce: 

1. Open terminal window
2. Execute `testground daemon`
3. Open another terminal window
4. Execute `testground plan import --from ./plans/network`
5. `testground run single --plan=network --testcase=ping-pong  --builder=docker:go --runner=local:docker --instances=2`

Expected result: 
- Results info log should be provided with status of executed test plan (success/fail/etc.)

Actual result:
- No logs for results like `INFO run finished successfully ...`

Note:

I initially thought these logs should be visible after collecting logs. However, `results.out` are empty, too

**Comment by hacdias** [comment]
Hey! Testground, by default, runs asynchronously. To get logs live, you have to append the flag `--wait`. You can also fetch a list of the current tasks with `testground tasks`.

If you also want to collect a tarball with the logs outputted by your run, you either append `--collect`, as well as `--wait`, or you wait until the execution of the run ends and execute `testground collect --runner local:docker [run-id]`.

Let me know if you need more help!

**Comment by Bidon15** [comment]
Hey! Thanks for the hint @hacdias 
Indeed --wait helped a lot with following up on what is happening in the running test plan terminal.
Though, I still don't get the idea why the results.out files are empty on both 0/1 after execution of the test plan 
Overall logs are clearly indicating that everything is fine
`{"ts":1639132301477845363,"msg":"","group_id":"single","run_id":"c6pip2gnt2ojiuff6v7g","event":{"success_event":{"group":"single"}}}`

Or does results mean the execution of the plan itself with no report on fail/pass/skip for test cases/scenarios?

**Comment by Bidon15** [comment]
Oh, I guess I found the answer myself: `At the moment Testground doesn't provide any tools for post-processing of outputs. You are free to submit ideas and pull requests and contribute to this feature`

I assume it's still true,  so I'll close this issue
