### ISSUE TITLE
Install Testground locally and run some test plans

### ISSUE THREAD

**Issue by nonsense** [testground/testground#1291]
Familiarize yourself with Testground and run a few testplans locally.

TODO:
- [ ] Read https://docs.testground.ai/ - What is Testground?
- [ ] Read https://docs.testground.ai/ - Concepts and Architecture
- [ ] Read https://docs.testground.ai/ - Getting started
- [ ] Install Testground locally
- [ ] Run `network:ping-pong` testplan locally (via the `local:docker` runner)

Invidiaul completion signoff:
- [x] @brdji
- [x] Nikola
- [x] Dimitrije
- [x] @galargh 
- [x] @laurentsenta
- [x] @dektech

**Comment by galargh** [comment]
Marking this as done since everyone has signed off already.
