### ISSUE TITLE
Support more platforms/archs

### ISSUE THREAD

**Issue by nonsense** [testground/testground#1298]
At the moment Testground is compiled against `amd64`. Given that Testground depends heavily on Docker, we should extract the arch component and make sure Testground can be configured to work on other platforms, such as `arm64`, too.

Related: https://github.com/testground/testground/pull/1297 ; https://github.com/testground/testground/issues/1263

**Comment by laurentsenta** [comment]
@nonsense I'll open with a naive question:

What is wrong with "just" removing the arch parameters as in https://github.com/testground/testground/pull/1296 ?
Is there code that is amd64 / arm dependent?

I lack context and the first commit about `amd64` is https://github.com/testground/testground/commit/76aabf7 
It makes me think this might be a copy and paste that we could live without.


Note to self, might be useful later:
https://docs.docker.com/desktop/multi-arch/#build-multi-arch-images-with-buildx could be useful.

**Comment by nonsense** [comment]
Removing the ARCH env var is probably fine. I don't remember why we had to be explicit and whether this is relevant anymore. If removing it doesn't break anything, we should certainly go it.

**Comment by laurentsenta** [comment]
@lalexgap it's not actively worked on right now, but it's great to hear your team is using it,

- have you made any changes to the sync-service project? (it's pulled on `make install`)
- if you're using it and it's stable, do you mind creating a PR or bumping https://github.com/testground/testground/pull/1296 ?
