### ISSUE TITLE
Investigate Testground networking requirements

### ISSUE THREAD

**Issue by KatarinaKeti** [testground/testground#1312]

**Comment by KatarinaKeti** [comment]
https://docs.google.com/document/d/1-Ur1PwktSov-iJp28MhGKk_i6nf-8eHJ-SRyPpS8lis/edit#heading=h.re10wj9pgayn

**Comment by mxinden** [comment]
@KatarinaKeti mind moving the content of the above Google doc to a GitHub issue? Allows everyone to read, join the discussion and subscribe to any changes.

**Comment by KatarinaKeti** [comment]
@mxinden Yeah, of course!

**Comment by KatarinaKeti** [comment]
CNI research

Testground requirements

All Testground runners except for the local runner have two networks: a 'control' and a 'data' network.

Test instances communicate with each other over the 'data' network.

Test instances communicate with the 'sync' service, and only the 'sync' service, over the 'control' network.

Therefore in order to use Kubernetes as our cluster management platform, we need a networking implementation that allows us to run multiple networks and attach multiple network interfaces to pods and containers.

Pod networking

A pod is a collection of containers; all these containers of the same collection share a network stack. Kubernetes manages that by setting up the network itself on the pause container, which you will find for every pod you create. All other pods attach to the network of the pause container which itself does nothing but provide the network. 
Therefore, it is also possible for one container to talk to a service in a different container, which is in the same definition of the same pod, via localhost.

When a cluster goes multi-node, the main challenge is communication between Pods across different nodes. Pods come and go. The size of cluster could increase or decrease as well. 
The network solutions come in two network types: overlay network based on encapsulation, or non-overlay networks, most likely using routing techniques. 
Common backends for for multi-host container networking solutions include VXLAN encapsulation, IPIP encapsulation, host-gw, IPSec.

CNI overview

CNI is an external module with a well defined interface that can be called by kubernetes to execute actions to provide networking functionality.

Container Networking Interface is responsible for providing network connectivity within a Kubernetes cluster for the applications to talk to each other.

CNI plugins, in general, allow the application’s traffic to pass through the host to a different application on the same host or different host within the cluster. 

Plugins are responsible for provisioning and managing an IP address to the interface and usually provide functionality related to IP management, IP-per-container assignment, and multi-host connectivity. The container runtime calls the networking plugins to allocate IP addresses and configure networking when the container starts and calls it again when the container is deleted to clean up those resources.

CNI clearly defines the specification for following activities:

  - When a Pod comes up, give it a network interface
  - Assign IP to the network interface
  - When a Pod is deleted, delete the associated network interface

The k8s POD network, as it is sometimes referred, provides connectivity between containers and nodes without address translation. The CNI plugin is part of the POD network which includes one or more containers and a CNI plugin running on each node that configure container connectivity dynamically when PODs are created and establish network connectivity between nodes.

We have a CNI configured at the time of deploying the cluster in this case called as the master CNI, this is usually the ‘eth0` interface in your pod, where Kubernetes service interacts with the pods. 
Now here comes the interesting part - in case there is a requirement of maintaining separate interfaces for monitoring, control-data plane separation or depending on the architecture requirements, there arises a need for attaching separate interfaces to your pods.

Reference CNIs

The CNI project maintains several reference CNI plugins. These consist of interface creation, IPAM, and other meta plugins. 
The reference CNIs use Linux kernel native functionality such as linux bridging, vlans, ipvan or macvlan. They typically “chain” the IPAM plugin to provide address management. 
The meta plugins provide additional networking functionality such as bandwidth control via Linux TC, firewalls and other linux networking functionality. These reference CNIs are often the foundation of k8s CNIs - Flannel, Weave, Calico, etc.

Problems With EKS VPC CNI

IP Limitations
The VPC CNI uses the subnet IP’s to allocate to the pods

Possible Solution: We can leverage the Custom Networking feature for separating the POD CIDR and the node CIDR. Disclaimer: Make sure you do this before the creation of the cluster.

Pod Density Limitations
Since the VPC CNI uses ENI’s for assigning the secondary IPs, it becomes limited to the number of pods that can be scheduled on the instances.
This even reduces if you are using custom networking, as the primary interface cannot be used for pod IP allocation.
Limits - https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt

Problems with Using any other CNI with EKS

If you go with your own CNI, AWS will not be supporting any issues related to networking, as they don’t manage it.

For every EKS cluster, AWS launches the control plane in a VPC which is managed by AWS, which is also explained in the AWS docs. 
What the doc doesn’t explain is that at the time of creation, a route table entry for your VPC CIDR to the ENI used to connect to your VPC is also created. 
This is how the API server is able to communicate to all the Nodes and pods in the cluster, but if we decide to use our own CNI, like calico, we change the POD CIDR, and now the API server has no clue on how to route the traffic to the pod IP.
Multus

Typically, in Kubernetes each pod only has one network interface (apart from a loopback); with Multus you can create a multi-homed pod that has multiple interfaces. This is accomplished by Multus acting as a "meta-plugin", a CNI plugin that can call multiple other CNI plugins.

This allows pods to connect to multiple networks over different interfaces and each interface would be using its own CNI plugin. Note that the CNI plugin can be the same or different. It all depends upon the requirement and implementation.

Multus is a CNI that actually is not a network interface itself. It orchestrates multiple interfaces and without an actual network configured - pods couldn’t communicate with multus alone. 
So multus is an enabler for multi device and multi subnet networks. Multus itself basically calls the real CNI instead of the kubelet and communicates the results back to the kubelet.

Multus supports all reference plugins (eg. Flannel, DHCP, Macvlan) that implement the CNI specification and 3rd party plugins (eg. Calico, Weave, Cilium, Contiv). In addition to it, Multus supports SRIOV, DPDK, OVS-DPDK & VPP workloads in Kubernetes with both cloud native and NFV based applications in Kubernetes.

However, on EKS, it is only supported when using the Amazon VPC CNI as the primary CNI. AWS does not support the Amazon VPC CNI when used for higher order interfaces, secondary or otherwise.
The current version of EKS support for Multus bundles Amazon VPC CNI as the default delegate plugin (which is the only supported and validated default  delegate plugin). The default delegate plugin configures the primary network interface (eth0) for pods to enable Kubernetes control plane traffic, including the IP Address Management (IPAM) for the primary network interface for the pods.

Multus installation

"Default network" - This is your pod-to-pod network. This is how pods communicate among one another in your cluster, how they have connectivity. Generally speaking, this is presented as the interface named eth0. This interface is always attached to your pods, so that they can have connectivity among themselves. We'll add interfaces in addition to this.

"CRDs" - Custom Resource Definitions. Custom Resources are a way that the Kubernetes API is extended. We use these here to store some information that Multus can read. Primarily, we use these to store the configurations for each of the additional interfaces that are attached to your pods.

This installation method requires that you first have installed Kubernetes and have configured a default network -- that is, a CNI plugin that's used for your pod-to-pod connectivity.

The recommended quickstart method to deploy Multus is to deploy using a Daemonset (a method of running pods on each nodes in your cluster), this spins up pods which install a Multus binary and configure Multus for usage.

git clone https://github.com/k8snetworkplumbingwg/multus-cni.git && cd multus-cni

We'll apply a YAML file with kubectl from this repo.

cat ./deployments/multus-daemonset-thick-plugin.yml | kubectl apply -f -

Validate the installation:

kubectl get pods --all-namespaces | grep -i multus

Complete guide and doc can be found here - https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/quickstart.md

Note: currently testing this one - https://github.com/aws-samples/eks-install-guide-for-multus

DPDK, SRIOV, VxLAN

DPDK gives you control of a NIC, bypassing the kernel completely, so you have to write code to do everything yourself. Generally people only use it when they need to do something very specific in a highly performant manner.

People new to networking and packet processing likely vastly underestimate just how complex the kernel networking stack is and how much it does for you: routing, network ACLs, TCP/IP, special packet handling (ARP, ICMP, LLDP), IPSec, etc.

VXLAN is a popular method of routing Layer 2 traffic across a network, it does this by simply encapsulating the frame and sending it as a UDP packet.

SR-IOV is a hardware standard that allows a PCI Express device – typically a network interface card (NIC) – to present itself as several virtual NICs to a hypervisor.

Why Do We Need Overlay Networks?

Overlay networks such as vxlan or ipsec encapsulate the packet into another packet. This makes entities addressable which are outside of the scope of another machine.
Alternatives to overlay networks include L3 solutions such as macvtap(lan) or even L2 solutions such as ivtap(lan), but these come with limitations or even unwanted side effects.

Links

https://github.com/aws-samples/eks-install-guide-for-multus
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI
https://www.digihunch.com/2021/06/kubernetes-networking-solutions-overview/
https://medium.com/thermokline/how-to-choose-a-k8s-cni-plugin-771edf4842c0
https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/quickstart.md
https://www.calsoftinc.com/blogs/2019/12/a-primer-on-multus-cni.html
https://github.com/kubernetes-sigs/kubespray/blob/master/docs/multus.md
https://medium.com/@nitinbedazzled/introduction-and-setting-up-multus-34ece7ba780b
https://medium.com/codeops/installing-weave-cni-on-aws-eks-51c2e6b7abc8
https://blog.neuvector.com/article/advanced-kubernetes-networking
https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-multus-cni/
https://www.cni.dev/plugins/current/
https://joealford.medium.com/deploying-multus-into-amazons-eks-42269146f421
