### ISSUE TITLE
Explore EKS custom networking solutions

### ISSUE THREAD

**Issue by KatarinaKeti** [testground/testground#1314]
Considering the AWS' recommendations regarding networking, that when using Multus the _VPC_ CNI should serve as the primary network interface. This means that we have the flexibility of choosing the secondary solution. 
Ideally, we would be able to allow Weave to serve as a secondary CNI as a starting point, with the ability of choosing additional supported ones by specifying an annotation on the pods where such configuration is necessary.

We should explore possibilities and limitations of the setup.

**Comment by KatarinaKeti** [comment]
This issue was transferred from the second sprint because work on it is still ongoing.

**Comment by laurentsenta** [comment]
Closing this issue as deprecated,
feel free to re-open if this deserve a new discussion.
