### ISSUE TITLE
Explore EKS's limitations

### ISSUE THREAD

**Issue by KatarinaKeti** [testground/testground#1315]
EKS' support for Multus is still in its early stages. Furthermore, we are obliged to utilize the underlying infrastructure in a way that AWS supports it. 

We need to observe and document all of the limitations of the new setup under the AWS' EKS.

**Comment by KatarinaKeti** [comment]
This issue was transferred from the second sprint because work on it is still ongoing.

**Comment by brdji** [comment]
As we have started wrapping up the EKS cluster deployment, I am closing this task.  The cluster performance reports can be found here:
https://github.com/testground/testground/issues/1410

More information on what the main roadblocks were can be found in these issues:
https://github.com/testground/testground/issues/1451
https://github.com/testground/testground/issues/1452
https://github.com/testground/testground/issues/1453
https://github.com/testground/testground/issues/1454
https://github.com/testground/testground/issues/1455
https://github.com/testground/testground/issues/1456
https://github.com/testground/testground/issues/1457
https://github.com/testground/testground/issues/1458
https://github.com/testground/testground/issues/1459
https://github.com/testground/testground/issues/1460
https://github.com/testground/testground/issues/1461

The final missing piece is to fix whatever is blocking test instances (pods) from modifying their data network connection parameters. This is evident in this issue (ping-pong test):
https://github.com/testground/testground/issues/1416
