### ISSUE TITLE
Run EKS with custom networking

### ISSUE THREAD

**Issue by KatarinaKeti** [testground/testground#1317]

**Comment by AbominableSnowman730** [comment]
We've been able to run EKS with `Multus` and `ipvlan` as a secondary network. Pods were able to communicate to each other over both networks. [These](https://docs.aws.amazon.com/eks/latest/userguide/pod-multiple-network-interfaces.html) are the considerations and the general guidelines on how to perform the task. As described in the guide, `ipvlan` is the generic solution used for the secondary network interface.
