### ISSUE TITLE
Deploy and test Weave with Multus

### ISSUE THREAD

**Issue by KatarinaKeti** [testground/testground#1325]

**Comment by AbominableSnowman730** [comment]
Weave has been deployed as a secondary network interface on top of the Multus installation mentioned in #1317 . Weave configuration is mapped to the one used in the [infra repo](https://github.com/testground/infra/) as close as possible. Multus seems to be compatible with Weave as the secondary network. 
While the installation itself posed no complex issues, there's a problem with pods being able to communicate to each other through weave's network interface. Resolving the issue will be covered in #1333 .
