### ISSUE TITLE
Resolve any additional issues with running Testground on EKS

### ISSUE THREAD

**Issue by Kale98** [testground/testground#1331]
The changes required for this functionality will be covered on the following branch _tmp_eks_cluster_.

**Comment by KatarinaKeti** [comment]
_Ongoing task_

This issue is something that will last and for this reason, it is transferred from sprint to sprint.

**Comment by brdji** [comment]
All that is left is to fix whatever is causing issue #1416 .
Once that is complete, we will prepare a PR for all the required changes and close this issue.

**Comment by brdji** [comment]
All that is left is to fix whatever is causing issue #1416 .
Once that is complete, we will prepare a PR for all the required changes and close this issue.

**Comment by laurentsenta** [comment]
Closing since there is no clear deliverable for this, and most of it is being tackled in https://github.com/testground/infra/pull/78 and https://github.com/testground/testground/pull/1350 I guess.
