### ISSUE TITLE
Run Testground on the new cluster

### ISSUE THREAD

**Issue by Kale98** [testground/testground#1334]
After provisioning an EKS cluster with Multus enabled (and a secondary network attached to the test pods), perform a successful test plan run on it.

**Comment by dektech** [comment]
Testground scripts have been successfully modified, so we were able to deploy EBS, EFS, and the testground daemon on the cluster with multus.
But as explained in a different issue, testground runs are not able to connect with the redis instance running on the cluster.

**Comment by KatarinaKeti** [comment]
Testground ping-pong test was performed successfully on the EKS cluster. This was done with utilizing Multus CNI, where _aws-vpc_ network was the primary one, and _ipvlan_ the secondary one. 
Furthermore, allocating different network interfaces of different CNIs can be done with pod annotations, which simplifies the process to a great degree. Ideally, we would be able to introduce multiple CNI solutions, and utilize them within different test scenarios. This would give us an opportunity to benchmark various CNIs in determination of the optimal one (most likely different test cases may benefit from using different CNI solutions).

**Comment by laurentsenta** [comment]
Link to change for later reference: https://github.com/testground/testground/compare/master...tmp_eks_cluster
