### ISSUE TITLE
Create PR of documentation changes

### ISSUE THREAD

**Issue by KatarinaKeti** [testground/testground#1342]
## What defines this endeavour to be complete?

<!--Create a check list of what you expect to see as part of delivering on the ask--

- [ ] Item 1
- [ ] Item 2
- [ ] ...

**Comment by dektech** [comment]
PRs already merged:
- https://github.com/testground/docs/pull/13
- https://github.com/testground/infra/pull/71
- https://github.com/testground/testground/pull/1375
