### ISSUE TITLE
Weave as the secondary CNI

### ISSUE THREAD

**Issue by KatarinaKeti** [testground/testground#1363]
## Description

Since we've already established a successful internode communication using ipvlan as the secondary CNI, we would like to now test this model with Weave.

## What defines this endeavour to be complete?

<!--Create a check list of what you expect to see as part of delivering on the ask--

- [ ] Item 1
- [ ] Item 2
- [ ] ...

**Comment by dektech** [comment]
This was successfully tested on two different clusters:
- using AWS VPC CNI as the primary CNI
- using Calico as the primary CNI (instead of AWS VPC CNI).
