### ISSUE TITLE
Add support for Test Plans written in JavaScript

### ISSUE THREAD

**Issue by daviddias** [testground/testground#137]
Requirements:
- Implement the SDK in JS

Alternative:
- Compile the SDK into WebAssembly and use it from Node

**Comment by daviddias** [comment]
@achingbrain this feature is getting more and more valuable as opportunities such as https://github.com/ipfs/testground/issues/235#issuecomment-564436069 appear :)

**Comment by laurentsenta** [comment]
I believe this is done, see also https://github.com/testground/testground/issues/1266
