### ISSUE TITLE
Upgrade terraform aws provider to a newer version supported by all architectures.

### ISSUE THREAD

**Issue by sysrex** [testground/testground#1376]
#### Version information:
Present in all versions.

Affected platforms:
Mac M1.

#### Description:
Executing terraform to create both EFS and EBS creation scripts will fail as terraform aws provider version 2.50 does not have a arm variant.

**Comment by laurentsenta** [comment]
Thanks for raising this @sysrex,

if you managed to fix this,
any chance you could open a PR so we can get this into master?

**Comment by sysrex** [comment]
@laurentsenta  - https://github.com/testground/infra/pull/74 , I've tested it and it works.

**Comment by laurentsenta** [comment]
Awesome, thanks for contributing!
