### ISSUE TITLE
Test new cluster connectivity

### ISSUE THREAD

**Issue by KatarinaKeti** [testground/testground#1388]
## Description

This issue is about the newly deployed cluster using Calico as primary, and Weave as secondary CNI.
We have successfully tested internode communications using both CNIs, now we need to deploy testground to the cluster and run the storm test for example.

## What defines this endeavour to be complete?

<!--Create a check list of what you expect to see as part of delivering on the ask--

- [ ] Item 1
- [ ] Item 2
- [ ] ...

**Comment by dektech** [comment]
This has been completed successfully for up to 250 instances of the storm test. When testing with 270 instances, the test can finish but starts showing CPU errors, which would mean we are close to the hardware limits of the cluster (2x c5.4xlarge instances).
