### ISSUE TITLE
Leveldb: not found

### ISSUE THREAD

**Issue by brdji** [testground/testground#1418]
#### Version information:
`commit 7f19d7282bf1662bf3649d2efa6ec83dd2b7aa88`

Architecture: `amd64`
OS: `Ubuntu 20.04.4`

#### Description:

Starting the daemon produces the following error:
` ERROR	error while popping task from the queue	{"err": "leveldb: not found"}`

I believe this is due to a bad (or missing) LevelDb installation on my machine, but I haven't found working instructions on how to install LevelDb

**Comment by laurentsenta** [comment]
What do you see when you use the branch `fix/issue-1418-leveldb-not-found`?

`git checkout origin/fix/issue-1418-leveldb-not-found && make goinstall && testground daemon`

**Comment by brdji** [comment]
1. This is the result of the stat command:
```
File: tasks.db/
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 10305h/66309d	Inode: 548866      Links: 3
Access: (0755/drwxr-xr-x)  Uid: ( 1000/   brdji)   Gid: ( 1000/   brdji)
Access: 2022-08-03 15:56:14.417299594 +0200
Modify: 2022-08-03 15:56:14.417299594 +0200
Change: 2022-08-03 15:56:14.417299594 +0200
 Birth: -
```
2. After completing performing step 3. the errors seem to have disappeared.

**Comment by brdji** [comment]
The cause of the issue is that we attempt to delete a key that is not present in the LevelDb, and not that LevelDb itself is not found.
Closing this.

**Comment by GlenDC** [comment]
Sorry to post in a closed issue, but I want to say that i Had the same behaviour as you described here, even though I am on latest master. Doing your step (3) of https://github.com/testground/testground/issues/1418#issuecomment-1203819103 still "fixes" it for me :)
