### ISSUE TITLE
Failed to send batch to InfluxDB

### ISSUE THREAD

**Issue by bokimilinkovic** [testground/testground#1428]
After the plan has successfully executed, I expected to see results pushed to InfluxDB,
All containers have been running and influx-db have been exposed to port 8086
`influxdb:1.8                   "/entrypoint.sh infl…"  Up 15 minutes   0.0.0.0:8086->8086/tcp    testground-influxdb
`
In Dockerfile I added one command that is providing right ENV as: 
`ENV INFLUXDB_URL="testground-influxdb:8086"
`
But still receiving error:
 _MESSAGE << sidecar      >> InfluxDB unavailable; no metrics will be dispatched: no InfluxDB URL in $INFLUXDB_URL env var_

Could it been that the sidecar and influxdb container are not running on the same network so therefore communication can not be established?

**Comment by laurentsenta** [comment]
Thanks for reaching out @bokimilinkovic,

Could you share your testground version? 
A description of your test plan, and the commands & configuration you used? The easier it is to reproduce your issue, the faster we can help you.

**Comment by bokimilinkovic** [comment]
Hello @laurentsenta Thanks for fast response!
Testground version: 
_Git commit: a068f0b9_

I imported plans from 
https://github.com/testground/learning-example-tg

`testground plan import --from . --name tg-learning`

$ testgrounda daemon
$ testground run single --plan tg-learning --testcase tg-sync-1to1 --builder docker:generic --runner local:docker --instances 2
