### ISSUE TITLE
Verify `kill` command is working as intended and write a help topic

### ISSUE THREAD

**Issue by brdji** [testground/testground#1433]
## Description

We are unsure if the `kill` command is working as intended in all scenarios (e.g. kill a timeouted task).
There is also no information on how to use the command:
```
$ testground kill --help
No help topic for 'kill'
```

## What defines this endeavor to be complete

- [ ] Test the `kill` command on a task that is in the queue
- [ ] Test the `kill` command on a task that is being run, but has timeouted 
- [ ] Write a help topic on how to use the `kill` command: note usage, options, etc.

Linked to #1417

**Comment by StefanGajic** [comment]
Kill command works as intended both from dashboard and from API for runners.
To test it locally from dashboad after starting `testground daemon` simply go to `http://localhost:8042/tasks ` and below actions click the `kill` button to kill the task, the page will refresh and task will be killed.
To use it from API after we run a test we can see its ID in last line and in another terminal window we use command  `curl http://localhost:8042/kill?task_id=`taskID and replace taskID with ID of the task we want to kill. Some tasks are being run pretty quick so we may need to have fast hands also to kill it.

Below is scenarios I tested to see how `kill` command works. 

`kill` command works on a task that is in the queue.

`kill` command works on a task that is being run, but has timeouted.

`kill` command works when two or more tasks are being started and then we decide to kill a specific task.
