### ISSUE TITLE
docs site: quick start - parameters and test case outdated code

### ISSUE THREAD

**Issue by GlenDC** [testground/testground#1447]
## Description

Code snippet for smallbrain/bigbrain main.go file seems to be out of date,
this code and explanation is found at https://docs.testground.ai/writing-test-plans/paramaters-and-testcases.

## What defines this endeavour to be complete?

Documentation is updated with correct snippets.

## Proposed Fixes

The following snippet is a version that does seem to work:

```go
package main

import (
	"github.com/testground/sdk-go/run"
	"github.com/testground/sdk-go/runtime"
)

var testcases = map[string]interface{}{
	"bigbrain":   run.InitializedTestCaseFn(runTestCase),
	"smallbrain": run.InitializedTestCaseFn(runTestCase),
}

func main() {
	run.InvokeMap(testcases)
}

func runTestCase(runenv *runtime.RunEnv, initCtx *run.InitContext) error {
	var (
		num     = runenv.IntParam("num")
		word    = runenv.StringParam("word")
		feature = runenv.BooleanParam("feature")
	)

	runenv.RecordMessage("I am a %s test case.", runenv.TestCase)
	runenv.RecordMessage("I store my files on %d servers.", num)
	runenv.RecordMessage("I %s run tests on my P2P code.", word)

	if feature {
		runenv.RecordMessage("I use IPFS!")
	}

	return nil
}

```

Note that besides this I also had to:

- update my `go.mod` file and rename the module (e.g. `testground-tutorial`)
  - mentioning it here as I do not see this instruction mentioned anywhere in the tutorial page
- After this I had to run `go mod tidy`

Doing all this does make the following command work:

```
testground run single --plan quickstart \
                        --testcase smallbrain \
                        --builder exec:go \
                        --runner local:exec \
                        --instances 1
```

Adding this issue here as that is what your instructions seem to request at the start of your docs.
If you wish I can also contribute it msyelf.

**Comment by Bidon15** [comment]
Hey @GlenDC ! 

There is a caveat in the docs page. The link you posted in the issue is pointing to the latest(but outdated) release v0.5.3. 
Latest master https://docs.testground.ai/v/master/writing-test-plans/paramaters-and-testcases has a different example. 

I've looked through the code-snippet in the docs' page based on master and it looks similar to what your proposal looks like: 
```go
package main

import (
	"github.com/testground/sdk-go/run"
	"github.com/testground/sdk-go/runtime"
)

func main() {
	run.InvokeMap(map[string]interface{}{
		"bigbrain":   test,
		"smallbrain": test,
	})
}

func test(runenv *runtime.RunEnv) error {
	var (
		num     = runenv.IntParam("num")
		word    = runenv.StringParam("word")
		feature = runenv.BooleanParam("feature")
	)

	runenv.RecordMessage("I am a %s test case.", runenv.TestCase)
	runenv.RecordMessage("I store my files on %d servers.", num)
	runenv.RecordMessage("I %s run tests on my P2P code.", word)

	if feature {
		runenv.RecordMessage("I use IPFS!")
	}

	return nil
}

```

Regarding the go.mod file, I guess this is already on the radar https://github.com/testground/testground/issues/1424
Cheers

**Comment by GlenDC** [comment]
Perfect. Looks good indeed in the master version.

https://github.com/testground/testground/issues/1448 can be closed together with this one this case.

I do recommend to do one or multiple of the following:

- use master by default for the docs: you document that you do not provide binaries, as such it will be quite common for people that read these docs to also in fact be on master;
- add to the location where you talk about dragons in documentation that people make sure to also check the master version fo documentation first prior to making a remark;
- make it more obvious that the doc version is linked to a version (e.g. when not on master, or latest, to have some kind of notification on top "hey there's also a master version, check it out?" or w/e, dunno :) For now it wasn't really obvious to me until someone said this to me,  but perhaps it's just me;

**Comment by laurentsenta** [comment]
👍 thanks for the note, capture in #1471
