### ISSUE TITLE
Cancelled runs in CI

### ISSUE THREAD

**Issue by MarcoPolo** [testground/testground#1545]
https://github.com/libp2p/test-plans/actions/runs/3635633357/jobs/6136235988 see the "Print the results" step

**Comment by MarcoPolo** [comment]
I can't assign this, but @laurentsenta and I talked about it.

**Comment by laurentsenta** [comment]
Running in CI with artifacts output to check the daemon's logs:
https://github.com/laurentsenta/test-plans/actions/runs/3656314247/jobs/6178614903

**Comment by MarcoPolo** [comment]
You couldn't reproduce any stalled/network errors? This happens to me every time.

**Comment by laurentsenta** [comment]
I can reproduce network / stalled errors on my machine, but I have seen the "canceled" status on CI only,
we talked about this on Slack, there are two different issues. These are the network issues: https://github.com/testground/testground/issues/1540 https://github.com/testground/testground/issues/1542

**Comment by laurentsenta** [comment]
@MarcoPolo, it seems that we're reaching the timeout, which is expected, see the notes in:
https://github.com/testground/testground/issues/1542#issuecomment-1352886909

When I fixed the runners, the tests were completed correctly.

I'm going to close this issue for now. Could you try the fix in the comment above and reopen it if you see that behavior again?
