### ISSUE TITLE
CI hangs for an hour before continuing

### ISSUE THREAD

**Issue by MarcoPolo** [testground/testground#1547]
See log here: https://github.com/libp2p/test-plans/actions/runs/3653171301/jobs/6172332096#step:9:3957

Notably:
```
Dec  9 00:17:52.626358	INFO	container exited	{"runner": "local:docker", "run_id": "ce97tbno4a4bonkf8u8g", "id": "534e4b61e4fe19819d3719a555b8e3047b072090cfdf0e3cf4f1c228e4582cda", "group": "go-v0.22.0sha256_262a9157453d4a2946119c8b3f0b16c1f16ab7c3017e1a7bdb08de06da75b0a1", "group_index": 0, "status": 0}
[3957](https://github.com/libp2p/test-plans/actions/runs/3653171301/jobs/6172332096#step:9:3958)
Dec  9 01:17:51.330689	INFO	result go-v0.22.0_x_go-v0.23.4_(quic)[ce97sm7o4a4bonkf8tvg]: success
```

There's an hour between those two logs for no obvious reason? This is despite setting `task_timeout_min = 2` in `.env.toml` [here](https://github.com/libp2p/test-plans/pull/85/files/9ca33d48998ed266ad34531c51ceb970517d9250#diff-a4be8b038cdc8f5d1acb785126532be6950d36a4be4fe48b3ab1ba49303247bdR31).

**Comment by laurentsenta** [comment]
There's a configuration error in your CI script, this is logged during the run step:

```
listen tcp 127.0.0.1:8042: bind: address already in use
 ```

During my test, the timeout is taken into account, more details here: https://github.com/testground/testground/issues/1542#issuecomment-1352886909

Two recommendations:
- we try to start 2 daemons in that repo, remove one,
- could you double check your `spawn(testground daemon)` does forward errors? When I try locally, `testground daemon` exits with status code = 1.
