### ISSUE TITLE
infra/k8s/eks: InfluxDB is not ready

### ISSUE THREAD

**Issue by ackintosh** [testground/testground#1553]
#### Version information:

- infra/k8s/eks/[testground_install.sh](https://github.com/testground/infra/blob/master/k8s/eks/testground_install.sh) on current master branch ([c3f09f1](https://github.com/testground/infra/commit/c3f09f1ae5cc51f450951beefb976911a832e2a6))
- Kubernetes version on EKS: 1.23 

#### Description:

The install script ([testground_install.sh](https://github.com/testground/infra/blob/master/k8s/eks/testground_install.sh)) finishes successfully but InfluxDB is not ready.

```shell
$ kubectl get deployments
NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
efs-provisioner           1/1     1            1           17m
influxdb                  0/1     1            0           16m
testground-daemon         1/1     1            1           15m
testground-sync-service   1/1     1            1           15m
```

It seems something of a problem with storage:

```shell
$ kubectl describe pods -l app.kubernetes.io/instance=influxdb
...
...
...
Events:
Type     Reason            Age                From               Message
 ----     ------            ----               ----               -------
Warning  FailedScheduling  86s (x4 over 31m)  default-scheduler  running PreBind plugin "VolumeBinding": binding volumes: timed out waiting for the condition
```

I checked for a PersistentVolumeClaim for InfluxDB and got the message:

> waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator

```shell
$ kubectl describe pvc -l app.kubernetes.io/name=influxdb
Name:          influxdb
Namespace:     default
StorageClass:  gp2
Status:        Pending
Volume:
Labels:        app.kubernetes.io/instance=influxdb
               app.kubernetes.io/managed-by=Helm
               app.kubernetes.io/name=influxdb
               helm.sh/chart=influxdb-2.6.1
Annotations:   meta.helm.sh/release-name: influxdb
               meta.helm.sh/release-namespace: default
               volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
               volume.kubernetes.io/selected-node: ip-192-168-24-57.ap-northeast-1.compute.internal
               volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       influxdb-7d4dc5c659-nhzlb
Events:
  Type    Reason                Age                    From                         Message
  ----    ------                ----                   ----                         -------
  Normal  WaitForFirstConsumer  59m                    persistentvolume-controller  waiting for first consumer to be created before binding
  Normal  ExternalProvisioning  4m22s (x222 over 59m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
```

From what I have seen, we should install [Amazon EBS CSI driver](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html).
> If you have a 1.22 or earlier cluster that you currently run pods on that use Amazon EBS volumes, and you don't currently have this driver installed on your cluster, then be sure to install this driver to your cluster before updating the cluster to 1.23.

> The Amazon EBS CSI driver isn't installed when you first create a cluster. To use the driver, you must add it as an Amazon EKS add-on or as a self-managed add-on.

**Comment by galargh** [comment]
As I understand this is resolved by https://github.com/testground/infra/pull/86. Is that correct?

Thank you for looking into this and finding a working solution :) Hugely appreciated!
