### ISSUE TITLE
Fix doc URLs

### ISSUE THREAD

**Issue by laurentsenta** [testground/testground#1555]
The doc website is offline: https://docs.testground.ai/
We switched to [docsify ](https://docs.testground.ai/) but we haven't updated the domain name yet,
the docs are available on github pages for now: https://testground.github.io/docs/master/

**Comment by laurentsenta** [comment]
(help desk reached out by @galargh, waiting for their answers)

**Comment by BigLep** [comment]
@laurentsenta @galargh : is this resolved?  https://docs.testground.ai/ loads for me

**Comment by galargh** [comment]
Yes, https://docs.testground.ai/ is ready. We want to also redirect https://testground.ai/ to https://docs.testground.ai/ but I'd consider this issue resolved.
