### ISSUE TITLE
testground plan run: Pool overlaps with other one on this address space

### ISSUE THREAD

**Issue by GlenDC** [testground/testground#1559]
#### Version information:

```
commit 433f4d3818f60f3195013d982477c6d8c080661f
```

```
$ system_profiler SPSoftwareDataType SPHardwareDataType
Software:

    System Software Overview:

      System Version: macOS 13.1 (22C65)
      Kernel Version: Darwin 22.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: <redacted>
      User Name: <redacted>
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 9 hours, 59 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro16,1
      Processor Name: 6-Core Intel Core i7
      Processor Speed: 2,6 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache: 768 KB
      L3 Cache: 6 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      System Firmware Version: 1916.60.2.0.0 (iBridge: 20.16.2059.0.0,0)
      OS Loader Version: 564.40.4~55
      Serial Number (system): <redacted>
      Hardware UUID: <redacted>
      Provisioning UDID: <redacted>
      Activation Lock Status: Enabled
```

#### Description:

Running any testplan, with the newest testground version I get the following problem:

```
Jan  6 08:15:50.651158  ERROR   doRun returned err      {"err": "task of type run cancelled: Error response from daemon: Pool overlaps with other one on this address space"}
Jan  6 08:15:50.651658  ERROR   task cancelled due to error     {"err": "task of type run cancelled: Error response from daemon: Pool overlaps with other one on this address space"}
```

First I thought it was related to a new plan I am developing for Libp2p, but even example (integration) tests are giving this error message 100% of the time (for me).

**Comment by GlenDC** [comment]
OK solved it myself. Turns out not to be a testground-specific issue. Seems some old networks were left from failed previous testruns...

I found them using `docker network ls` and afterwards I deleted any testplan-related network using `docker network rm`. Works all fine now.

Might want to add this to some FAQ somewhere?

**Comment by laurentsenta** [comment]
Thanks for sharing the fix,

> Might want to add this to some FAQ somewhere?

Definitely. Would you mind making a PR to https://github.com/testground/docs?

We're waiting for the [new doc website](https://github.com/testground/testground/issues/1555) but https://testground.github.io/docs/master/#/ should work in the meantime.
