### ISSUE TITLE
EBS CSI Driver Will fail if the cluster name is not `gossipsub`

### ISSUE THREAD

**Issue by sysrex** [testground/testground#1560]
This line assumes the cluster name is - gossipsub (https://github.com/testground/infra/pull/86/files#diff-aa5ed861dbdb20033f811e9d7c621ff1b9fc8ab8c7c333fb747d5a27fa7eae9bR265)

- I believe that should use string substitution to get the iam service account of `$CLUSTER_NAME`

**Comment by sysrex** [comment]
@ackintosh - would you want to take a look it maybe?

**Comment by ackintosh** [comment]
Oh, it's my fault. 🙇 I will file a PR to fix that.
