### ISSUE TITLE
Ambiguity in documentation on running testground first time

### ISSUE THREAD

**Issue by MuhtasimTanmoy** [testground/testground#1564]
The instructions for importing and running plans with `testground` specify that the `testground` command should be run from the host system, but it is not clear how to do this since there is no available `testground` binary. It is possible that these commands should be run from inside a container, but it is not clear how to do this either.

As per the documentation, we need to run the following commands for installing and running `testground`.
```
$ git clone https://github.com/testground/testground.git
$ cd testground
$ make install       # builds testground and the Docker image, used by the local:docker runner.
$ testground daemon
```
But the `make install` command builds a docker image from the source.
```
docker build --build-arg TG_VERSION=`git rev-list -1 HEAD` -t iptestground/testground:edge -f Dockerfile.testground .
```
And there is no available `testground` binary available to run the command `testground daemon`

So, for the following commands given below. Are we supposed to run them from inside a container? Though the first one is runnable, the second one is not runnable from there.
```
$ testground plan import --from ./plans/network

# run two instances of the `ping-pong` test case from the `network` plan,
# building with docker:go, running with local:docker
$ testground run single --plan=network --testcase=ping-pong \
                        --builder=docker:go --runner=local:docker \
                        --instances=2
```

It is not clear what is missing or how to correctly install and run testground. It is recommended to refer to updated documentation or seek support to resolve these issues.

Also, docs pointing to `docs.testground.ai` should be replaced with `https://testground.github.io`.

**Comment by laurentsenta** [comment]
Hi @MuhtasimTanmoy, thanks for reaching out,
we have #1430 planned, which will eventually make this simpler,

for now, let's unblock you:
`make install` calls `go install` https://github.com/testground/testground/blob/3a8563aefb41a4155ae202c4bb9a2b8f31e48f25/Makefile#L14 which should install the testground binary for you.

Does `make install` succeeds?

Could you ensure the folders listed in the [go install docs](https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies) contain the `testground` binary and are in your `PATH`?

> Executables are installed in the directory named by the GOBIN environment variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH environment variable is not set. Executables in $GOROOT are installed in $GOROOT/bin or $GOTOOLDIR instead of $GOBIN.

(thanks for raising the issue with the doc, [doc domain was fixed](https://docs.testground.ai/master/#/))

**Comment by MuhtasimTanmoy** [comment]
- Does make install succeeds?
    - Yes

- Could you ensure the folders listed in the [go install docs](https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies) contain the testground binary and are in your PATH?
    - The binary was available there. But the environment variable was not set. 
    - Manually setting that solved that issue. Thanks for pointing that out.
