### ISSUE TITLE
quickStart get failed message :  1 nodes failed

### ISSUE THREAD

**Issue by linlin1988** [testground/testground#1587]
## Description

hi , dear testground team

i followed the quickstart guide and get some error

this is my cmd 

1. testground daemon
2. testground plan create --plan=quickstart
3. testground -v -vv run single --plan=quickstart \
--testcase=quickstart \
--runner=local:exec \
--builder=exec:go \
--instances=1 \
--wait \

i just wait , and the redis\grafana\influxdb container is all OK

by finally get this result:

Aug 17 03:05:01.882309	INFO	created a synthetic composition file for this job; all instances will run under singleton group "single"
Aug 17 03:05:01.882481	INFO	using home directory: /home/admin/.config/testground
Aug 17 03:05:01.882855	INFO	.env.toml loaded from: /home/admin/.config/testground/.env.toml
Aug 17 03:05:01.882891	INFO	testground client initialized	{"addr": "http://localhost:8042"}

>>> Result:

Aug 17 03:05:01.957207	INFO	run is queued with ID: cjeosnfr7mco143upkcg

>>> Server output:

Aug 17 03:05:02.714442	INFO	performing build for groups	{"plan": "quickstart", "groups": ["single"], "builder": "exec:go"}
Aug 17 03:05:05.016142	INFO	build succeeded	{"plan": "quickstart", "groups": ["single"], "builder": "exec:go", "artifact": "/home/admin/.config/testground/data/work/exec-go--quickstart-8a5cf00919a0"}
Aug 17 03:05:05.016313	INFO	performing healthcheck on runner
Aug 17 03:05:05.028040	INFO	healthcheck: ok
Aug 17 03:05:05.028141	INFO	starting run	{"run_id": "cjeosnfr7mco143upkcg", "plan": "quickstart", "case": "quickstart", "runner": "local:exec", "instances": 1}
Aug 17 03:05:05.028571	INFO	starting test case instance	{"plan": "quickstart", "group": "single", "number": 0, "total": 1}
Aug 17 03:05:05.035183	INFO	0.0068s INTERNAL_ERR << single[000] >> unknown event: {<nil> <nil> <nil> <nil> <nil> <nil> <nil>}
Aug 17 03:05:05.035235	INFO	0.0070s INCOMPLETE << single[000] >> 
Aug 17 03:05:05.035829	WARN	run finished in error	{"run_id": "cjeosnfr7mco143upkcg", "plan": "quickstart", "case": "quickstart", "runner": "local:exec", "instances": 1, "error": "1 nodes failed"}

how should i do to figureout this error ?
thanks so much 

## my testground version

[admin@vm-203-66 quickstart]# testground version
Testground
Git commit: caa56145

## my system os

os:  CentOS Linux release 7.9.2009 (Core)

## my docker container 

96cc4dc83b58   iptestground/sync-service:edge   "/service"                About an hour ago   Up About an hour               0.0.0.0:5050->5050/tcp   testground-sync-service
129eecbb15aa   influxdb:1.8                     "/entrypoint.sh infl…"    2 hours ago         Up 2 hours                     0.0.0.0:8086->8086/tcp   testground-influxdb
ab6388a42e1a   redis                            "docker-entrypoint.s…"    2 hours ago         Up 2 hours                     0.0.0.0:6379->6379/tcp   testground-redis
0084f2c48faa   bitnami/grafana                  "/opt/bitnami/script…"    2 hours ago         Up 2 hours                     0.0.0.0:3000->3000/tcp   testground-grafana
1a58ae90c57c   goproxy/goproxy                  "/usr/bin/tini -- /g…"    2 hours ago         Up 2 hours                     8081/tcp                 testground-goproxy

## my quickstart code

/home/admin/.config/testground/plans/quickstart
notes:  without edit any file, these files are just auto gen by    create cmd
[admin@vm-203-66 quickstart]# ll
total 28
-rw-r--r-- 1 admin root    99 Aug 17 09:06 go.mod
-rw-r--r-- 1 admin root 13639 Aug 17 10:01 go.sum
-rw-r--r-- 1 admin root   368 Aug 17 09:06 main.go
-rw-r--r-- 1 admin root   687 Aug 17 09:06 manifest.toml

# main.go 

package main

import "github.com/ipfs/testground/sdk/runtime"

func main() {
        runtime.Invoke(run)
}

func run(runenv *runtime.RunEnv) error {
        runenv.RecordMessage("Hello, Testground!")
        return nil
}

hope to receive your reply 

best gegards

**Comment by linlin1988** [comment]
my local exec go version


[admin@vm-203-66 plans]# go version
go version go1.19.10 linux/amd64

**Comment by Bidon15** [comment]
Hey @linlin1988 👋 
Thanks for the issue. I'd recommend you trying out 'local:docker' or 'docker:generic' instead of exec 

We will stop supporting exec env in the future updates of testground

**Comment by linlin1988** [comment]
ok , thanks , i'll try the docker way
