### ISSUE TITLE
Missing and mismatching APIs from Core API and Go IPFS API

### ISSUE THREAD

**Issue by hacdias** [testground/testground#235]
In order to implement everything else that is missing on #93, we need to solve some challenges relative to the Core API and Go IPFS API.

### Missing APIs

There are a lot of missing APIs that we need from both or from only one:

- Files Write
- Repo Stat
- GC
- UrlStore Add
- FileStore Ls

### Mismatches! Different APIs!

The ideal would be to run the same test against the external daemon and the in-process instance. However, since Core API (`interface-go-ipfs-core`) and `go-ipfs-api` interfaces differ, it won't be possible.

I see this old issue (https://github.com/ipfs/go-ipfs-api/issues/38) where it is discussed the implementation of Core API. So, as far as I understand, the goal is to use **interface-go-ipfs-core** on all API interfaces, correct?

I could work on adding the missing functions to `interface-go-ipfs-core` and then work on implementing those interfaces on `go-ipfs-api`. However, I'm pretty sure that it will take some time.

/cc @daviddias @Stebalien

**Comment by daviddias** [comment]
> I see this old issue (ipfs/go-ipfs-api#38) where it is discussed the implementation of Core API. So, as far as I understand, the goal is to use interface-go-ipfs-core on all API interfaces, correct?

This is correct. Although AFAIK, @Stebalien does want to revisit those APIs and create a better usage experience. I know that this is something that @alanshaw has thought a ton too.

Meanwhile, so that you don't get blocked, is there a practical way in which you can use the go-ipfs CLI to issue the commands so that you can test the features above?

**Comment by daviddias** [comment]
In parallel, @Stebalien, @alanshaw I think this will be an excellent opportunity to drive a revolution in our user facing APIs. We could have a Testground Plan that focuses on the API and:

- Tests go-ipfs as an library using the CoreAPI
- Tests go-ipfs as a daemon using go-ipfs-api
- Tests go-ipfs as a daemon using js-ipfs-http-client
- Tests js-ipfs as a instance (aka library using the CoreAPI)
- Tests js-ipfs as a daemon using js-ipfs-http-client
- Tests js-ipfs as a daemon using go-ipfs-api

Each test case would focus on an IPFS Subsystem API (Files, Network, etc), starting with Files. @hacdias can be our champion and iterate in both IPFS implementations given his JavaScript & Golang knowledge and growing js-ipfs and go-ipfs expertise. 

Having a Plan to test our API would create a coordination point between both implementations and ensure that both implementations progress together (it would be a ipfs/interop on a rocket 🚀)

**Comment by Stebalien** [comment]
> UrlStore Add

This one we can skip. You can use `go-ipfs-files.NewWebFile` to construct a file from a URL then pass the `NoCopy` option.

(documentation? what documentation?)

> FileStore Ls

I'd very much like to _avoid_ exposing this anywhere. The current filestore interface is a footgun that I don't want to stabilize.

**Comment by hacdias** [comment]
@daviddias yes, I can do the daemon tests with the IPTB inner APIs, running each command manually via `RunCmd` and parsing its output. It can be a bit clunky to check for errors, but it would work for now.

**Comment by daviddias** [comment]
Oh! Discovered that there is actually an go-ipfs client library that implements the CoreAPI, Look at that! https://github.com/ipfs/go-ipfs-http-client 👀

@hacdias you probably want to include this one in the mix as well.

**Comment by hacdias** [comment]
If we use that **instead** of `go-ipfs-api`, we can simply have one test running on the daemon and directly on the Core API. Unless @Stebalien does not recommend it. It explicitly says:

> This package is experimental and subject to change. If you need to depend on something less likely to change, please use go-ipfs-api. If you'd like the latest and greatest features, please use this package.

**Comment by daviddias** [comment]
@hacdias why not both client libraries for now?

**Comment by raulk** [comment]
This is irrelevant and outdated here now. If needed, discussion can be moved to https://github.com/ipfs/test-plans/.
