### ISSUE TITLE
Create a testplan to verify that peers can only communicate via the data network

### ISSUE THREAD

**Issue by Stebalien** [testground/testground#348]
We modify routes such that peers can only communicate with each-other via the data network. However, we don't actually have any tests to ensure that this happens.

We should create a new test under the "network" test plan where:

1. Both peers listen on the all address (both IPv6 and IPv4).
2. Both peers write all IP addresses _except_ those in the `runenv.TestSubnet` range to redis.
3. Both peers try to dial the IP addresses listed by the other peer.

If any of these connections succeed, fail the test plan.

**Comment by Stebalien** [comment]
@alanshaw this is a good way to get started learning testground (and it's not blocking anything else so it can wait until after async js has shipped). Intersted?

**Comment by nonsense** [comment]
We should not only create a testplan to verify, but actually fix this, because right now testplan instances are reachable on the control network (via the data network) - via the `default` route, for example:

```
/ # ping 100.96.4.18
PING 100.96.4.18 (100.96.4.18): 56 data bytes
64 bytes from 100.96.4.18: seq=0 ttl=64 time=30.153 ms
64 bytes from 100.96.4.18: seq=1 ttl=64 time=20.100 ms
64 bytes from 100.96.4.18: seq=2 ttl=64 time=20.087 ms
^C
--- 100.96.4.18 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 20.087/23.446/30.153 ms
/ # traceroute 100.96.4.18
traceroute to 100.96.4.18 (100.96.4.18), 30 hops max, 46 byte packets
 1  apn-31-0-0-0.dynamic.gprs.plus.pl (31.0.0.0)  10.058 ms  10.042 ms  10.026 ms
 2  100.96.4.18 (100.96.4.18)  20.048 ms  20.048 ms  20.039 ms
/ # ip route
default via 31.0.0.0 dev eth1
20.116.0.0/16 dev eth1 scope link  src 20.116.1.2
31.0.0.0 dev eth1 scope link
100.64.0.10 via 100.96.4.1 dev eth0
100.96.5.6 via 100.96.4.1 dev eth0
```

I think that deleting the `default` route might solve this, but we need to make sure we have routes to the full `data` network.
