### ISSUE TITLE
Test plan -  DHT + Bitswap

### ISSUE THREAD

**Issue by dirkmc** [testground/testground#465]
Write a plan that tests that we can transfer data using Bitswap + DHT

Goals:
- Verify that Bitswap can find peers using the DHT and transfer data to them, in a realistic environment

Plan:
- Create several nodes running the old DHT with the old Bitswap
- Create several nodes running the new DHT with the new Bitswap
- Nodes should have realistic latency / bandwidth that may be expected for internet nodes
- Seed data of the following sizes on 1, 2 (1 old / 1 new) and 4 nodes (2 old / 2 new):
  1MB, 2MB, 4MB, 8MB, 16MB, 32MB, 64MB, 128MB
- Fetch data of each size using
  - new node as a leech
  - old node as a leech

Acceptance Criteria:
- All data is transferred successfully within 4x the theoretical transfer speed
  eg if bandwidth is 10MB/s, latency is 100ms then a 10MB file can theoretically be transfered in 1.1s so test is successful if transfer occurs in < 4.4s

**Comment by dirkmc** [comment]
@Stebalien anything to add / change for this plan?

**Comment by dirkmc** [comment]
See ipfs/testground#345 for an example of a Bitswap Test Plan
Note: ipfs/testground#345 is currently not up to date with master pending logging being sorted out (as of Feb 4 2020)

**Comment by Stebalien** [comment]
> Create several nodes running the new DHT with the new Bitswap

For now, it'll just be the old DHT everywhere.

---

Other than that, the main thing we're testing here is whether or not bitswap finds content reliably. For that, we'll also need to do things like:

* Randomly disconnect nodes (e.g., everyone in a session) and see if we eventually reconnect or find other nodes.
* Have a situation where one node has all files in a directory except one and another node only has the one file (but not the directory). We _should_ switch over to this new peer.

**Comment by raulk** [comment]
Closing this here. If still relevant, please open under https://github.com/ipfs/test-plans/.

**Comment by LucaCampanile** [comment]
> Write a plan that tests that we can transfer data using Bitswap + DHT
> 
> Goals:
> 
> * Verify that Bitswap can find peers using the DHT and transfer data to them, in a realistic environment
> 
> Plan:
> 
> * Create several nodes running the old DHT with the old Bitswap
> * Create several nodes running the new DHT with the new Bitswap
> * Nodes should have realistic latency / bandwidth that may be expected for internet nodes
> * Seed data of the following sizes on 1, 2 (1 old / 1 new) and 4 nodes (2 old / 2 new):
>   1MB, 2MB, 4MB, 8MB, 16MB, 32MB, 64MB, 128MB
> * Fetch data of each size using
>   
>   * new node as a leech
>   * old node as a leech
> 
> Acceptance Criteria:
> 
> * All data is transferred successfully within 4x the theoretical transfer speed
>   eg if bandwidth is 10MB/s, latency is 100ms then a 10MB file can theoretically be transfered in 1.1s so test is successful if transfer occurs in < 4.4s

Hi 
I am very interested about this work where i can find them? I see there is a branch called ipfs e2e plan but didn't work
thanks for your reply

**Comment by nonsense** [comment]
@LucaCampanile most libp2p plans are migrated to https://github.com/libp2p/test-plans

**Comment by nonsense** [comment]
@LucaCampanile and Bitswap test plans specifically are at: https://github.com/ipfs/test-plans
