### ISSUE TITLE
create docker hub org for testground

### ISSUE THREAD

**Issue by nonsense** [testground/testground#472]
Right now we are using `ipfs/testground` which is under the `ipfsbot` account.

It'd be nice to have a testground Docker Hub organisation, so that we add all our images there - right now we have two images - one for sidecar and one for s3fs daemon.

**Comment by Stebalien** [comment]
For now, I've created a testground team under the ipfs org with admin access to the ipfs/testground images.

**Comment by raulk** [comment]
We now have https://hub.docker.com/orgs/iptestground/, and have invoked the Docker Hub Name Squatting Policy to reassign a better name.
