### ISSUE TITLE
`docker:go` builder: Allow cross-repo replace directives

### ISSUE THREAD

**Issue by Stebalien** [testground/testground#48]
Currently, they only allow selecting a branch. Ideally, I'd be able to point at a different repo or even a local directory.

**Comment by raulk** [comment]
👍 Context for whoever implements this:

* the dependency map is parsed from `--dep` CLI flags, which assume a format `<dependency>=<version>`
* the above dependency map is injected into the `Dependencies` field of the `build.Input` struct
* that struct is propagated into the builder's `Build()` method.
* the `docker:go` builder generates `replace` directives *duplicating* the module name, and setting its version to the passed one.

We should:

1. Adopt go.mod notation in the CLI `--dep` parameter: `<dependency>=[<target>]@<version>`. When `target` is missing, we assume no remapping of repos.
2. Adjust the components mentioned above. The `build.Input.Dependencies` field turn into a `map[string]DependencyTarget`, where `DependencyTarget` is a struct containing the target and version.
3. In the future, to preserve correctness, builders not supporting this feature (e.g. a hypothetical `docker:js` builder that relies on `npm install` and `package.json`) will need to return an error if DependencyTarget.Target is not empty.

**Comment by dgrisham** [comment]
Hey! I'm attempting to use a replace directive in the `go.mod` for a testground test, but it's currently failing. Would the above PR allow me to do this, or is there a way already? Seems like it should, but wanted to make sure / avoid making a new issue if this covers it. Thanks!

**Comment by hacdias** [comment]
Hello @dgrisham! Yes, I just merged the PR. I tested and it seemed to work. Please try out with master and let me know if you have problems. The syntax is as mentioned above: `--dep <dependency>=[<target>]@<version>`
