### ISSUE TITLE
reorganise modules + spin off to testground org

### ISSUE THREAD

**Issue by raulk** [testground/testground#485]
So releasing v0.1 was a pain due to the cross-dependencies between submodules of this repo, and the way go releases work by tagging. Particularly, this is the dependency graph.

```
testground
   |__ sdk/sync
   |    |__ testground (logging, this dep can be removed trivially)
   |__ sdk/runtime

sdk/iptb
   |__ sdk/runtime   
```

@nonsense and I had to:

1. Tag `sdk/runtime/v0.1.0` from master.
2. Update downstream go.mods to point to released `sdk/runtime v0.1.0`: https://github.com/ipfs/testground/pull/477/files.
2. Remove all local replace directives from all modules, and point to _yet unreleased_ `v0.1.0` of dependencies: https://github.com/ipfs/testground/pull/478/files
3. Tag v0.1.0 and hope for the best.

What I propose is the following:

1. Create a GitHub org for testground, placeholder name: `testground` (although occupied).
1. Create a ~`testground/go-sdk`~ `testground/sdk-go` repo. Consolidate `sync` and `runtime` into a single module and place it in that repo.
1. Migrate project-specific plans from here to ~`testground/go-plans`~ `libp2p/test-plans` and `ipfs/test-plans`. As it is, it makes little sense to release/tag them with the platform release, and testground is already using go-getter, precisely because I foresaw this situation early on.
1. Rename this repo to ~`testground/platform`~ `testground/testground`.

**Comment by dirkmc** [comment]
This sounds good to me - would it make sense to have different repos for each plan (so we don't need to date all plans at once when there is an API change)?
