### ISSUE TITLE
Branch CI is broken on force-push

### ISSUE THREAD

**Issue by Stebalien** [testground/testground#517]
When testing a _branch_, `TRAVIS_COMMIT_RANGE` is always `old_head..new_head`. Unfortunately, when force-pushing, `old_head` won't exist. This will cause the `before_install` "doc only" check to succeed and we'll abort the test with a success.

We should check to see if the commit range actually exists. If it doesn't, we should proceed with the test (or find some other commit range to test).

**Comment by nonsense** [comment]
We changed that at https://github.com/ipfs/testground/pull/512 , and I was not aware we are breaking `force-push` runs.

If I have to choose between CI running on doc only PRs, and force-push commits triggering correct CI runs, I would definitely pick the second one. Shall we revert, or? cc @decanus

**Comment by decanus** [comment]
@nonsense there is probably another way to do the check, actually you may find your solution going through here: https://github.com/facebook/react/issues/1768
