### ISSUE TITLE
Redis Writer Panics

### ISSUE THREAD

**Issue by aschmahmann** [testground/testground#547]
The sync.Writer panics if it fails to submit a keepAlive message. I've seen three different types of occurrences of this:

https://github.com/ipfs/testground/blob/a1a6d48560375d7f3b9570fdd8365e0017450c00/sdk/sync/write.go#L91-L97

1) Context cancellation

I suspect the issue is that we cancel before taking the lock here:

https://github.com/ipfs/testground/blob/a1a6d48560375d7f3b9570fdd8365e0017450c00/sdk/sync/write.go#L195-L200

2) Something like a redis lookup event

```
{"ts":1581578960316135616,"msg":"","group_id":"cypress","run_id":"8602414488a5","event":{"type":"message","message":"start provide loop"}}       panic: dial tcp: lookup redis-headless on 100.64.0.10:53: write udp 100.96.7.79:48445->100.64.0.10:53: write: invalid argument
goroutine 19 [running]:
github.com/ipfs/testground/sdk/sync.(*Writer).keepAlive(0xc0002920f0, 0xe558c0, 0xc0003440c0)
        /sdk/sync/write.go:95 +0x1d4
github.com/ipfs/testground/sdk/sync.(*Writer).keepAliveWorker(0xc0002920f0, 0xe558c0, 0xc0003440c0)
        /sdk/sync/write.go:79 +0x5c
created by github.com/ipfs/testground/sdk/sync.NewWriter
        /sdk/sync/write.go:69 +0x279
```

3) An I/O timeout

{"ts":1581624908918749128,"msg":"","group_id":"cypress","run_id":"9bd780077d08","event":{"type":"message","message":"keep alive err: attempt: 1, err: dial tcp: i/o timeout"}}

This was collected by a wrapper the retries the writer when there are errors.

**Comment by Stebalien** [comment]
We cancel before taking the lock so we can cancel an in-progress event. We definitely need to check to see if the context has expired before panicing.

However, the message is odd:

> panic: dial tcp: lookup redis-headless on 100.64.0.10:53: write udp 100.96.7.79:48445->100.64.0.10:53: write: invalid argument

I guess we could get an "invalid argument" error if the socket is closed? I'm concerned it could be some other DNS issue.

**Comment by raulk** [comment]
@Stebalien It _is_ another DNS issue. The target port in that panic is `udp/53`.

**Comment by Stebalien** [comment]
@raulk it could also be a canceled context causing us to abort/close something.

**Comment by aschmahmann** [comment]
@Stebalien @raulk I added a brief message from the I/O timeout. It looks like the error message emitted by redis for the tcp timeout is not nearly as detailed as the udp one is.

**Comment by Stebalien** [comment]
@aschmahmann there's a MaxRetries option that's currently set to 5 (in sdk/sync/common.go). You should try increasing that instead of manually retrying.

Also consider changing the timeouts in those options.

**Comment by raulk** [comment]
Was fixed in https://github.com/testground/testground/pull/841.
