### ISSUE TITLE
[proposal] versioned sdk api

### ISSUE THREAD

**Issue by coryschwartz** [testground/testground#570]
We should have versions with the SDK that correspond with testground releases.

Any time there are new interfaces, or new public methods, that will need to be in a new API version.

**Comment by coryschwartz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Versioned plan sdk](https://trello.com/c/8BN3rCOv/21-versioned-plan-sdk)

**Comment by raulk** [comment]
Was fixed with #485 and https://github.com/testground/testground/pull/883.
