### ISSUE TITLE
move build/image push to the k8s cluster

### ISSUE THREAD

**Issue by nonsense** [testground/testground#572]
When trying to use the cluster:k8s runner, the build/image push process is super slow if your upload speed is low.

We should come up with a way of building and pushing from a remote builder, rather than from the local developer machine, which has low upload bandwidth, because this increases the feedback loop with minutes.

**Comment by Robmat05** [comment]
Will be fixed in #849

**Comment by nonsense** [comment]
This is not done yet, there are at least 2 open PRs related to it.
