### ISSUE TITLE
Better API for network configuration

### ISSUE THREAD

**Issue by raulk** [testground/testground#645]
Migrating from #221.

> We should probably add a `SetupNetwork` shared utility function for setting initial latency/bandwidth restrictions.

Yes! Right now this is cumbersome; users have to deal with plumbing, we should create some porcelain/API sugar around this.

**Comment by Robmat05** [comment]
Still needs best team mate to be assigned

**Comment by raulk** [comment]
This was implemented in https://github.com/testground/sdk-go/pull/5 and https://github.com/testground/sdk-go/pull/12 🎉
