### ISSUE TITLE
EnsureContainer pulls images unnecessarially.

### ISSUE THREAD

**Issue by coryschwartz** [testground/testground#682]
If PullImageIfMissing is set to true, and the container is not created, the image is pulled regardless of whether it is necessary.

Consider the following:

Starting with a clear docker environment
```
docker system prune -a
```

I pull an image I know is used by testground.
```
docker pull redis
Using default tag: latest
latest: Pulling from library/redis
68ced04f60ab: Pull complete 
7ecc253967df: Pull complete 
765957bf98d4: Pull complete 
91fff01e8fef: Pull complete 
76feb725b7e3: Pull complete 
75797de34ea7: Pull complete 
Digest: sha256:ddf831632db1a51716aa9c2e9b6a52f5035fc6fa98a8a6708f6e83033a49508d
Status: Downloaded newer image for redis:latest
docker.io/library/redis:latest
```

now, I should expect that the testground daemon does not need to pull it again. And yet, it does.

**Comment by raulk** [comment]
The `EnsureContainer` function was overhauled in https://github.com/testground/testground/commit/b5c70e1ea580140a44bb61d88b9ad39d7e920642, and now the caller can pass in an `ImageStrategy` to decide whether it wants to do nothing, pull or build the image if it doesn't exist locally.
