### ISSUE TITLE
Bring your own Dockerfile builder

### ISSUE THREAD

**Issue by coryschwartz** [testground/testground#692]
I know this was here at one time, and was done away with. If there was a builder for which the user could supply their own Dockerfile, plan writers could more easily modify the test environment. 

Bifrost runs ipfs with a web proxy in front of it, in some cases with url rewriting.

Lots of home users will run ipfs from behind firewalls.

Additionally, infrastructure applications could be added by test composition.
For example, browser IPFS may require additional proxies, preloaders, or other infrastructure which is not provided by the current test suite, and need not be provided most of the time. With a "bring your own Dockerfile" builder, this additional infrastructure could be added as a build composition.

**Comment by coryschwartz** [comment]
This issue is similar to https://github.com/ipfs/testground/issues/49

I had a slightly different implementation in mind when I wrote this, than what they have in that ticket, but either method would accomplish the same goal.

**Comment by Robmat05** [comment]
Should this be something that lives in our v0.4 sprint backlog? Or is this just a kind of reminder that this needs work in a future sprint. Just a bit more info on where this should live would be helpful to understanding our work load for the current sprint
