### ISSUE TITLE
multi-builder composition

### ISSUE THREAD

**Issue by coryschwartz** [testground/testground#693]
Be able to run tests with a combination of builders, as well as version differences.

Once javascript and browser builders are added, we will want to be able to test with mixtures of go, node, and browser js versions.

**Comment by raulk** [comment]
@Robmat05 what's the reason this ended up in milestone v0.4?

**Comment by Robmat05** [comment]
Cory told me that he would like to get to it in v0.4. It never go out of the backlog, so I do believe it’s better labeled as Important but Unplanned

**Comment by raulk** [comment]
A composition is self-contained. It's the specification of a job. Making compositions multi-builder or multi-runner would make them lose that property, as now the user would need to specify which runner or builder they actually want to use. The user can already specify which builders and runners are enabled for a test plan in its manifest file, along with builder and runner options.
