### ISSUE TITLE
Configurable pushgateway addressses

### ISSUE THREAD

**Issue by coryschwartz** [testground/testground#711]
Currently, the address of of the pushgateway is hard-coded to 'http://prometheus-pushgateway'

This address is resolvable on the k8s and docker environments, where services or containers
are resolvable. It is not so easily resolvable on the local:exec runner, where the service
will run on localhost.

this should be re-done to match what we do with the redis endpoint, generating an environment variable for the address relevant to each runner.

@raulk explains the desired behavior here: https://github.com/ipfs/testground/pull/704/files#r394284656

**Comment by coryschwartz** [comment]
Right now there are six different files that have this address now hard-coded. I should feel bad about it. And I do.

**Comment by nonsense** [comment]
We stopped using the pushgateway, so this can be closed.
