### ISSUE TITLE
Move config from env vars to .env.toml

### ISSUE THREAD

**Issue by nonsense** [testground/testground#713]
Currently we have required testground config in `.env.toml` and also in `environment variables`. We should consolidate config for testground at one place - either .env.toml or environment variables, but having both required is not user-friendly.

This is a problem for `kops` and `kubectl`. For `kubectl` there is no action required right now (even though we just pick the default context from ~/.kube). For `kops` we should probably update `func (c *ClusterK8sRunner) healthcheckK8s()` to use a specific cluster name, and not expect the cluster name to be set in an env var.

**Comment by raulk** [comment]
This is important as it reduces friction and WTF moments.

**Comment by nonsense** [comment]
I am closing this, because we removed `kops` from the healthchecks, and we no longer rely on environment variables being set so that Testground works as expected.
