### ISSUE TITLE
fork Pushgateway to add concept of _sessions_

### ISSUE THREAD

**Issue by raulk** [testground/testground#748]
Hoisted from https://github.com/ipfs/testground/issues/745#issuecomment-604962698.

---

I'm thinking about forking pushgateway in order to add the concept of _sessions_.

1. When starting, a test plan would open a _session_, associated with the groupings it has picked.
2. It would push its metrics under that grouping.
3. Upon end, it would close the _session_.

On the pushgateway side:

1. Opening a _session_ causes us to track if those metrics have been scraped by Prometheus.
    * Every time new metrics are pushed, we reset `scraped[session_id]=false`.
    * Every time Prometheus scrapes us (we identify Prometheus by the [`User-Agent`](https://github.com/prometheus/prometheus/pull/2447) and the `Accept` headers), we set `scraped[session_id]=true`.
2. Closing a _session_ causes us to expunge all the metrics associated with the _session_ once `scraped[session_id]=true`.

**Comment by nonsense** [comment]
We decided to move away from Pushgateway.
