### ISSUE TITLE
client-side test plan management

### ISSUE THREAD

**Issue by raulk** [testground/testground#750]
Once we implement #747, in order to achieve #749, we'll need to provide some CLI goodness to manage test plans at the client side.

Supported sources: Git repos and filesystem.

## Potential CLI

  - `testground plan add --name foo --from git://...`
  - `testground plan add --name foo --from file://...`
  - `testground plan switch --name foo --to branch_a`
  - `testground plan switch --name foo --to master`
  - `testground plan remove --name foo`

## Notes

- `switch` only works on git origins.
- `add` for git origins would clone the upstream into managed source directory under `$TESTGROUND_HOME/plans_src`.
- `add` for local filesystem origins would symlink into `$TESTGROUND_HOME/plans_src`.

**Comment by raulk** [comment]
@Robmat05 why did you close this as discarded?

**Comment by Robmat05** [comment]
I meant to close #745, but these tickets were right next to each other and this was a keystroke error. ugh. Nice catch, thanks
