### ISSUE TITLE
Evaluate using a push model with InfluxDB or Elasticsearch as our store.

### ISSUE THREAD

**Issue by Robmat05** [testground/testground#755]
We need to look at this evaluation with an unbiased analysis on which application we should use as we decide to move to event based and metrics/stats reporting.

Analysis criteria should include (but not limited to):

- Reliability, at current volume and at scale
- Supplemental work required to on-board application
- Cost, at current volume and at scale
- Comparative performance (robustness)

**Comment by Robmat05** [comment]
1st plan for testing InfluxDB:

1. Set up a InfluxDB Cloud: https://www.influxdata.com/products/influxdb-cloud/
2. Modify the benchmark test plan to stop using Prometheus, and instead record point-in-time observations via RecordMetric.
3. At the end of the test, process the stdout file in the outputs directory, collect all metrics and push them in batches to InfluxDB.
4. See how well this performs.
In the future, we can use Vector to do the log processing and pushing (https://vector.dev/), but right now this is the quickest way to test drive this stack.

**Comment by coryschwartz** [comment]
The infra team has an influxdb cloud account; is there any benefit of having them in the same place, compare test results with real results, etc.

Working on getting the benchmark plan migrated

**Comment by raulk** [comment]
@coryschwartz not really. Any comparison will be done at the Grafana level, which can pull from many data sources. Whatever is quickest.

**Comment by coryschwartz** [comment]
Thanks, I think I'll have a PR to share tonight,  at least good enough to do some basic evaluation

**Comment by coryschwartz** [comment]
@raulk check out the two draft PRs linked here. both are capable of pushing metrics into influxdb, and both are in quite terrible condition, but are functioning.

**Comment by coryschwartz** [comment]
@raulk I can give you a demo of either one of these if you want.

It's easy to push more data than the free tier on influx cloud so I rate-limited the the collect method PR.

**Comment by Robmat05** [comment]
This ticket has come OFF of the priority critical path for the upcoming release as other feature/bugs have leapfrogged its priority.

I am placing this back into  ‘Selected for Dev’ so that we may be able to pick it back up prior to release date once higher priority tasks are resolved.

**Comment by raulk** [comment]
We ended up selecting InfluxDB as our main metrics store. Prometheus has been relegated to infrastructure monitoring only. We may introduce Elasticsearch later to centralise infrastructure logs.

Thanks @coryschwartz and @nonsense for your input.

See #907 for the general direction, and https://github.com/testground/sdk-go/pull/3/ for concrete API design.
