### ISSUE TITLE
Testground v0.5 launch documentation - Writing Test Plans, Page

### ISSUE THREAD

**Issue by Robmat05** [testground/testground#810]
Draft to be uploaded to Gitbook site: https://app.gitbook.com/@protocol-labs/s/testground

**Comment by coryschwartz** [comment]
I added a "quickstart" page. It's not much, but it's a start!

https://app.gitbook.com/@protocol-labs/s/testground/test-plan-sdk/quickstart

**Comment by coryschwartz** [comment]
I've gottten a few articles written regarding writing plans. 

In addition to the quickstart page, I have written the following tutorials 

* Environment Variables
* Parameters and TestCases
* Keeping instances in sync
* Communication between instances

The last two, will need some edits once changes to the sync service have landed.

**Comment by coryschwartz** [comment]
I'll update the sync and commnunication pages tomorrow and proably close out this ticket. @rauil did some re-organization over this past weekend, and the gitbook is starting to fill out.
