### ISSUE TITLE
Testground v0.5 launch documentation - Building Test Plans, Page

### ISSUE THREAD

**Issue by Robmat05** [testground/testground#811]
Draft to be uploaded to Gitbook site: https://app.gitbook.com/@protocol-labs/s/testground

**Comment by coryschwartz** [comment]
I wrote this page a couple of weeks ago 
https://app.gitbook.com/@protocol-labs/s/testground/builders/builders

This page has an explanation for how to build plans. There is a separate page (which is not written at this time) about running plans ( https://app.gitbook.com/@protocol-labs/s/testground/running-test-plans)

For running `single` plans, it is typical to build in the same phase as run. I think this can be counted as complete given the builder section has examples for running the builder on its own.
