### ISSUE TITLE
Start Annotating AWS Clusters to gather metric data

### ISSUE THREAD

**Issue by Robmat05** [testground/testground#865]
We as a team should figure out a method of annotating AWS clusters that we are using by the project/team that our work is spent on.  This way we can predict usage and cost forecasts as well as eventually differentiate billing by respective project/teams

**Comment by nonsense** [comment]
I think just by adding a `Team` tag, along all EC2 resources, it should then be possible to filter these on AWS billing page.

**Comment by nonsense** [comment]
I've added `TEAM` and `PROJECT` tags to all resources that are created with our scripts. We just need to inform the teams about them when we release v0.5

<img width="579" alt="Screenshot 2020-04-22 at 19 51 23" src="https://user-images.githubusercontent.com/50459/80015928-b8ffec80-84d2-11ea-930a-e1bb987a3865.png">

I've added them under `cost allocation tags`:

<img width="1368" alt="Screenshot 2020-04-22 at 19 51 55" src="https://user-images.githubusercontent.com/50459/80016010-d1700700-84d2-11ea-857d-c8068a08d8d3.png">

I guess after a day or so, we should be able to filter based on these 3, which should give enough granularity.

Related: https://github.com/testground/infra/pull/19

**Comment by Robmat05** [comment]
Thank you, this is very helpful
