### ISSUE TITLE
migrate from Travis to CircleCI

### ISSUE THREAD

**Issue by raulk** [testground/testground#881]
The migration to `testground/testground` wasn’t automatic for Travis... Rather than set it up, I’m thinking this is a perfect moment put Travis to bed and migrate to CircleCI.

**➡️ See thoughts on #802.**

And maybe while we're on it, we could run some experiments with their Kubernetes integration? Relates to #879.

**Comment by coryschwartz** [comment]
Kubernetes support is limited to EKS (and other hosted providers) it looks like.

**Comment by nonsense** [comment]
> Kubernetes support is limited to EKS (and other hosted providers) it looks like.

I think there is some misunderstanding here - it looks to me that CircleCI supports Kubernetes deployment in the sense of continuous delivery.

What we want is to run tests on Kubernetes (obviously as fast as possible), and not carry the cost of running a 24/7 Kubernetes cluster for test purposes (if this is possible).

To me this is rather different to what I see available in CircleCI.

**Comment by Robmat05** [comment]
Windows portion not covered in #897 is now being worked in #900

**Comment by coryschwartz** [comment]
I had left this open while the billing was still not setup correctly.

Now that we have billing, I've enabled docker layer caching, and the CI speed has improved! Improviing the CI speed is, after all, the whole purpose for switching to circle.

This ticket is now concluded by this ticket, which sets up DLC: https://github.com/testground/testground/pull/905
