### ISSUE TITLE
consider setting a different min/max worker nodes

### ISSUE THREAD

**Issue by nonsense** [testground/testground#922]
Requesting N number of nodes on AWS, sometimes results in N-10 nodes, or N+10 nodes.

For example:

<img width="1680" alt="Screenshot 2020-04-28 at 16 43 56" src="https://user-images.githubusercontent.com/50459/80501396-ad4b7480-896f-11ea-83ad-16ba5166ddf4.png">

<img width="1429" alt="Screenshot 2020-04-28 at 16 43 19" src="https://user-images.githubusercontent.com/50459/80501408-b0defb80-896f-11ea-8f9f-4195070eb44d.png">

<img width="832" alt="Screenshot 2020-04-28 at 16 43 12" src="https://user-images.githubusercontent.com/50459/80501421-b4728280-896f-11ea-8440-ca2f932480c1.png">

---

We should consider updating our infra scripts to allow for a variable number of nodes in the cluster. For example the user should be able to request 220-250 VMs, and Testground should work with any number of nodes in the middle.

**Comment by Robmat05** [comment]
Parking this in v0.6 so as to initiate discussion on Hardening Epic
