### ISSUE TITLE
hardening: cli: migrate arguments to flags

### ISSUE THREAD

**Issue by raulk** [testground/testground#930]
With the migration from v1 to v2 of https://github.com/urfave/cli performed in https://github.com/testground/testground/pull/928, the parsing behaviour has changed, such that all flags are expected before the args. This is, in theory, more POSIX compliant, but it affects the UX we had designed.

See https://github.com/urfave/cli/blob/master/docs/migrate-v1-to-v2.md#flags-before-args.

Unfortunately, READMEs and docs were not updated when that patch was merged, causing beginner instructions to break. To avoid bad experiences, we reverted that PR and subsequent related ones while we sort this out.

## Examples of suboptimal user experience

**Before:**

```
./testground run single benchmarks:subtree --instances 25 --builder docker:go --runner local:docker
```

Reads like an order:

> testground, run a single group of the benchmarks:subtree test case, with 25 instances, builder docker:go, and runner local:docker"

**After:**

```
./testground run single --instances 25 --builder docker:go --runner local:docker benchmarks:subtree
```

Reads weird. It forces you to think about parameters, builders, runners, etc. before even declaring the test case you want to run.

## Proposal

Migrate all arguments to flags. This also helps us get rid of the `:` convention:

```
./testground run single --plan benchmarks --testcase subtree --instances 25 --builder docker:go --runner local:docker
```

## Definition of done

- [x] Implement the migration of args to flags.
- [x] Update all READMEs and docs.
- [x] Update integration tests.

**Comment by coryschwartz** [comment]
README updated, in https://github.com/testground/testground/pull/938 but not the gitbook
