### ISSUE TITLE
SDK: Metrics – support resetting Timers and Counters

### ISSUE THREAD

**Issue by raulk** [testground/testground#937]
The default go-metrics timers and counters do not reset themselves on collection. The timer uses some form of exponential decay or EWMA, and counters are monotonically increasing.

Conversely, resetting variants are useful to track latencies or hits between collection events.

See https://github.com/ethereum/go-ethereum/tree/master/metrics for inspiration. My suspicion is that we do not need to fork the entirety of go-metrics, we can just add write new structs that implement the corresponding interfaces upstream.

cc @nonsense

**Comment by nonsense** [comment]
Related: https://github.com/testground/sdk-go/pull/14

**Comment by nonsense** [comment]
So this is now done. One will be able to view an example on the benchmarks dashboard, once the `storm` testcase is completed at https://github.com/testground/testground/pull/877
