### ISSUE TITLE
improve `checkClusterResources` in cluster_k8s.go

### ISSUE THREAD

**Issue by nonsense** [testground/testground#944]
Currently this function is not accurate, and it'd be nice if we have immediate feedback on available resources for `requests` on the cluster, prior to starting pods.

**Comment by nonsense** [comment]
We will have to revamp this once we introduce the autoscaler.

**Comment by Robmat05** [comment]
Discarded, as we will create an equivalent ticket for this functionality within the Supervisor Requirement features of TaaS
