### ISSUE TITLE
Consider how to introduce network partitioning functionality in Testground

### ISSUE THREAD

**Issue by nonsense** [testground/testground#975]
Filecoin will need soon network partitioning functionality. We should consider how to implement this. It could be done on the:
- application-side (libp2p swarm)
- network-side (network rules, as envisioned in the sidecar)
- through weave npc maybe

The main problem is: how do we write a testplan that introduces a network partition at a given point, so that nodes on either side of the partition can still talk to each other. We should consider how to do that when connections are already established, and the partition is temporary, and the problem goes away after a certain period of time.

**Comment by raulk** [comment]
The data model for this is already in place in the sdk `[network` package](https://pkg.go.dev/github.com/testground/sdk-go@v0.2.1/network?tab=doc#LinkShape). Test instances can set specific filter actions (DENY, ACCEPT) for specific subnets.

However, the sidecar is currently not doing anything with those settings. I guess we need to:

- [ ] Provider helper methods to calculate IP addresses we want assigned to ourselves, within a particular subnet of the test run's subnet.
  * Instances in the A side of the partition calculate IP addresses in a subnet `/24` out of the test run's `/16`.
  * Instances in the B side get a different `/24` subnet.
  * We use the sync service to decide which gets which.
- [ ] Instances request network configuration changes that DENIES the other subnet.
  * Sidecar needs to support this, I guess via `iptables`.
