### ISSUE TITLE
 Integration tests for docker:go builder.

### ISSUE THREAD

**Issue by Robmat05** [testground/testground#999]
Please see epic description for details on test specifics

**Comment by coryschwartz** [comment]
Do we expect to mock docker or to depend on docker? I think the latter. This would be a test that ensureContainer, etc does what they claim to. My estimation is a single day to bring the test coverage higher.

**Comment by coryschwartz** [comment]
I started writing tests for the docker in https://github.com/testground/testground/pull/1009. We can add unit tests for the builder itself, or as already discussed, a larger integration test would cover this component also.
